phpro/grumphp

.travis.yml
README.md
composer.json
resources/config/services.yml
spec/GrumPHP/Task/PhpcsfixerSpec.php
src/GrumPHP/Task/Phpcsfixer.php

There is very cool tool [PHP-CS-Fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer) it allows to fix codestyle errors automatically.

Added Php-cs-fixer support

---

spec/GrumPHP/Task/PhpunitSpec.php
src/GrumPHP/Task/Phpunit.php

First of great tool!
I wanted to use this with a library not containing a `phpunit.xml` file. It does however have a `phpunit.xml.dist` file to which phpunit would resolve if the first was not found. ([documentation](https://phpunit.de/manual/current/en/textui.html#textui.examples.filter-shortcuts)). 
Removing the default setting allows packages to ship with a more basic config.

Allow phpunit to resolve the default config

---

.travis.yml

HHVM nightly is no longer supported on Ubuntu Precise. See travis-ci/travis-ci#3788 and facebook/hhvm#5220

HHVM nightly is no longer supported on Travis

---

spec/GrumPHP/Collection/TasksCollectionSpec.php
spec/GrumPHP/Console/Helper/TaskRunnerHelperSpec.php
spec/GrumPHP/Runner/TaskRunnerSpec.php
spec/GrumPHP/Task/BehatSpec.php
spec/GrumPHP/Task/BlacklistSpec.php
spec/GrumPHP/Task/Context/GitPreCommitContextSpec.php
spec/GrumPHP/Task/PhpcsSpec.php
spec/GrumPHP/Task/PhpcsfixerSpec.php
spec/GrumPHP/Task/PhpspecSpec.php
spec/GrumPHP/Task/PhpunitSpec.php
src/GrumPHP/Collection/TasksCollection.php
src/GrumPHP/Console/Application.php
src/GrumPHP/Console/Command/Git/PreCommitCommand.php
src/GrumPHP/Console/Helper/PathsHelper.php
src/GrumPHP/Console/Helper/TaskRunnerHelper.php
src/GrumPHP/Runner/TaskRunner.php
src/GrumPHP/Task/Behat.php
src/GrumPHP/Task/Blacklist.php
src/GrumPHP/Task/Context/ContextInterface.php
src/GrumPHP/Task/Context/GitPreCommitContext.php
src/GrumPHP/Task/Phpcs.php
src/GrumPHP/Task/Phpcsfixer.php
src/GrumPHP/Task/Phpspec.php
src/GrumPHP/Task/Phpunit.php
src/GrumPHP/Task/TaskInterface.php

This major refactoring has some BC breaks.
It is possible to specify which task can run in which context.
A console helper is created that is responsible for running the tasks in the console commands.
This way it is easy to reuse the taskrunner in multiple console commands: You will only need to pass a new context.
This PR will make it possible to develop #33.
@aderuwe, @igormukhingmailcom : Can you please review and tell me if you like it or not?

Refactoring for running the tasks in different contexts

---

README.md
resources/config/services.yml
resources/hooks/commit-msg
resources/hooks/pre-commit
spec/GrumPHP/Task/Context/GitCommitMsgContextSpec.php
spec/GrumPHP/Task/Git/CommitMessageSpec.php
src/GrumPHP/Console/Application.php
src/GrumPHP/Console/Command/Git/CommitMsgCommand.php
src/GrumPHP/Console/Command/Git/DeInitCommand.php
src/GrumPHP/Console/Command/Git/InitCommand.php
src/GrumPHP/Console/Command/Git/PreCommitCommand.php
src/GrumPHP/Console/Helper/TaskRunnerHelper.php
src/GrumPHP/Task/Context/GitCommitMsgContext.php
src/GrumPHP/Task/Git/CommitMessage.php

This commit adds a new git hook: `commit:msg`.
You will be able to match patterns to git commit messages.
In the future additional tasks like a check on username etc. can be added. (For example: user vagrant can not commit)
What do you think @aderuwe, @igormukhingmailcom  ?
It's not a code-quality task, but it is always nice to have some control about the commit messages.
For example validating a jira issue number in the commit msg etc.

Commit message task

---

src/GrumPHP/Task/Phpunit.php

Some tests throw exceptions with the message 'Unable to guess the Kernel directory.' In symfony.
I don't know why (I thought -c is the same as --configuration), but changing this, fixes the problem.

phpunit task modifications

---

README.md

Remove version for less documentation maintenance.
This will allow composer to determine the last stable version. 
```sh
$ composer require phpro/grumphp
Using version ^0.4.1 for phpro/grumphp
./composer.json has been created
Loading composer repositories with package information
...
```

Remove version for less documentation maintenance.

---

spec/GrumPHP/Task/PhpcsfixerSpec.php
src/GrumPHP/Task/Phpcsfixer.php

As --config value shadow the configuration used in the file selected by --config-file
and we was using always the default --config=default in the process,
the config in the file was never used

Unset the default value for the config option

---

composer.json
spec/GrumPHP/Task/BehatSpec.php
spec/GrumPHP/Task/CodeceptionSpec.php
spec/GrumPHP/Task/Git/BlacklistSpec.php
spec/GrumPHP/Task/Git/CommitMessageSpec.php
spec/GrumPHP/Task/GruntSpec.php
spec/GrumPHP/Task/PhpcsSpec.php
spec/GrumPHP/Task/PhpcsfixerSpec.php
spec/GrumPHP/Task/PhpspecSpec.php
spec/GrumPHP/Task/PhpunitSpec.php
src/GrumPHP/Task/AbstractExternalTask.php
src/GrumPHP/Task/Behat.php
src/GrumPHP/Task/Codeception.php
src/GrumPHP/Task/Git/Blacklist.php
src/GrumPHP/Task/Git/CommitMessage.php
src/GrumPHP/Task/Grunt.php
src/GrumPHP/Task/Phpcs.php
src/GrumPHP/Task/Phpcsfixer.php
src/GrumPHP/Task/Phpspec.php
src/GrumPHP/Task/Phpunit.php
src/GrumPHP/Task/TaskInterface.php

This PR replaces the `getDefaultConfiguration()` method with a `getConfigurableOptions()` method.
By using the Symfony `OptionsResolver`, it is now easier to configure tasks in `grumphp.yml`.
When you type a typo or add a wrong configuration type, the resolver will complain and tell you what to do.

Make it easier to configure task.

---

doc/parameters.md

The default parameter value for `bin_dir` was wrong. I changed it to `./vendor/bin`.

updated default parameter value

---

README.md
doc/events.md
doc/parameters.md
resources/config/parameters.yml
resources/config/services.yml
resources/config/subscribers.yml
spec/GrumPHP/Configuration/GrumPHPSpec.php
spec/GrumPHP/Event/RunnerEventSpec.php
spec/GrumPHP/Event/RunnerFailedEventSpec.php
spec/GrumPHP/Event/Subscriber/StashUnstagedChangesSubscriberSpec.php
spec/GrumPHP/Event/TaskEventSpec.php
spec/GrumPHP/Event/TaskFailedEventSpec.php
src/GrumPHP/Configuration/ContainerFactory.php
src/GrumPHP/Configuration/GrumPHP.php
src/GrumPHP/Console/Application.php
src/GrumPHP/Event/RunnerEvent.php
src/GrumPHP/Event/RunnerFailedEvent.php
src/GrumPHP/Event/Subscriber/StashUnstagedChangesSubscriber.php
src/GrumPHP/Event/TaskEvent.php
src/GrumPHP/Event/TaskFailedEvent.php
src/GrumPHP/Runner/TaskRunner.php

Introducting the ignore_unstaged_changes parameter that saved unstaged files to the stash before running the pre-commit tasks.
More information can be found in #100.
**Note that this PR will result in some BC breaks!!!**

Introducting the ignore_unstaged_changes parameter.

---

spec/GrumPHP/Collection/ProcessArgumentsCollectionSpec.php
src/GrumPHP/Collection/ProcessArgumentsCollection.php
src/GrumPHP/Task/Git/Blacklist.php

| Fixed tickets | #124 
This ticket contains an additional option to add an array of arguments but with a separated entry for the value itself. This can be handy to create options like: `'-e' 'pattern'`
This commit also fixes the git blacklist task.

Fix git blacklist task

---

doc/tasks/phpcs.md
src/GrumPHP/Task/Phpcs.php

| Fixed tickets | #129
This PR will remove the default PSR2 configuration from PHPCS and use the built-in phpcs defaults instead.

Phpcs: Don't use the PSR2 standard by default.

---

doc/commands.md
doc/parameters.md
resources/hooks/local/commit-msg
resources/hooks/local/pre-commit
resources/hooks/vagrant/commit-msg
resources/hooks/vagrant/pre-commit
spec/GrumPHP/IO/ConsoleIOSpec.php
spec/GrumPHP/Locator/ChangedFilesSpec.php
src/GrumPHP/Console/Command/Git/CommitMsgCommand.php
src/GrumPHP/Console/Command/Git/PreCommitCommand.php
src/GrumPHP/IO/ConsoleIO.php
src/GrumPHP/Locator/ChangedFiles.php

| Fixed tickets | #144
This PR makes it possible to pass the raw git diff output to the `git:pre-commit` and `git:commit-msg` command of GrumPHP. When no raw diff input is added, the command will try to fetch the git diff through a separate git process.
This PR should also show the changed files when commiting through `git commit -a` and therefor fix #144.

Make it possible to use the raw git diff as input in the git hooks.

---

spec/GrumPHP/Console/Helper/PathsHelperSpec.php
src/GrumPHP/Console/Application.php
src/GrumPHP/Console/Command/Git/InitCommand.php
src/GrumPHP/Console/Helper/PathsHelper.php
src/GrumPHP/Locator/ExternalCommand.php
src/GrumPHP/Util/Composer.php

| Fixed tickets | #140, #145
As mentioned in the fixed ticket, the project commands should have priority to the globally installed commands. To make sure that the project bin-dir is always checked first, the PATH variable is altered. This also happens while running the commands as composer plugin. 
After this PR is merged, both the composer plugin and the CLI tool will work exactly the same.
To improve the generated GIT hooks, the external commands are made relative if the command is located in the project. If the external command is not located in the project, the absolute path will be used.

Improve external command locator

---

README.md
doc/parameters.md
resources/config/parameters.yml
resources/config/services.yml
spec/GrumPHP/Configuration/GrumPHPSpec.php
spec/GrumPHP/Process/ProcessBuilderSpec.php
src/GrumPHP/Configuration/GrumPHP.php
src/GrumPHP/Process/ProcessBuilder.php

| Fixed tickets | #149 
This PR makes it possible to configure the process timeout globally. If your task is taking a long time to run, this setting might be a life saver!

Configurable process timeout parameter

---

doc/tasks/xmllint.md
spec/GrumPHP/Task/XmlLintSpec.php
src/GrumPHP/Task/XmlLint.php

This PR adds the option to specify the file extensions for the xml linter. Using this, it's possible to include *.xsd, *.wsdl and other extensions

added triggered_by option for xml linter

---

doc/tasks/phpunit.md
spec/GrumPHP/Task/PhpunitSpec.php
src/GrumPHP/Task/Phpunit.php

| Branch        | /
| Fixed tickets | #166 
**About:**
Could we get an option for the phpunit task that could specify the groups the would like to run?
it would be very helpful.
**something like this:**
```yaml
phpunit:
config_file: tests/phpunit.xml
groups: [small, fast]
metadata:
priority: 200
```

[FEATURE] add functionality to phpunit task --group

---

spec/GrumPHP/Formatter/PhpCsFixerFormatterSpec.php
src/GrumPHP/Formatter/PhpCsFixerFormatter.php

On windows, the arguments are escaped with a `"` rather than a `'`.  This fix uses the argument escaper to escape the arguments we're stripping out correctly, so that it detects and strips them out correctly.

Escape arguments we're stripping out

---

doc/tasks/php_cs_fixer2.md
src/GrumPHP/Task/PhpCsFixerV2.php

Without this fix cli can't be executed correctly

Fix PhpCsFixerV2 doc + using_cache option not correctly set

---

doc/tasks.md
doc/tasks/git_conflict.md
spec/GrumPHP/Task/Git/ConflictSpec.php
src/GrumPHP/Task/Git/Conflict.php

A friend of mine @cafferata came up with this idea. Implement a new task which checks if your current working directory (repository) has any merge conflicts. It's a simple task and there's nothing special to it. I though it was a good idea, so I implemented it. Got the GIT command out of [StackOverflow](http://stackoverflow.com/questions/3065650/whats-the-simplest-way-to-git-a-list-of-conflicted-files)
What do you guys think of this idea? Maybe we can make this idea better?

Added new feature: GIT Conflict task

---

spec/GrumPHP/Collection/ProcessArgumentsCollectionSpec.php
src/GrumPHP/Collection/ProcessArgumentsCollection.php
src/GrumPHP/Task/PhpMd.php

[PHPMD expects multiple source files to be comma separated](https://github.com/phpmd/phpmd#using-multiple-source-files-and-folders). Currently the files are separated with spaces which makes PHPMD think that the second file is the report format it should use which results in an error (since the name of the second file is not a valid report format).
```shell
Running task  9/11: PhpMd
Aborted ...
Can't find the custom report class: path/to/the/second/File.php
```

Fix PhpMd task

---

src/GrumPHP/Task/PhpCpd.php

Currently (thanks to me) the `triggered_by` option isn't really doing anything so let's (ab?)use phpcpd's own `--names` parameter :)

Fix triggered_by config for PhpCpd task

---

doc/tasks/clover_coverage.md
doc/tasks/phpunit.md
spec/GrumPHP/Task/PhpunitSpec.php
src/GrumPHP/Task/Phpunit.php

This adds an option to always run PHPUnit tests, even if no PHP files were changed. Useful by itself, but also makes sure there's always something to retrieve coverage from.
Currently, for a freshly cloned/installed project, I won't get any coverage at all, it would just break the build.

Add an option to always execute PHPUnit

---

resources/config/tasks.yml

Seems like I sneaked in a typo in the `phpcpd` configuration which makes GrumPHP crash and burn in case-sensitive environments. Sorry about that! Maybe it would be a good idea to cover the configurations with tests somehow so CI will catch similar errors in the future?

Fix phpcpd in case-sensitive environments

---

doc/tasks/phpmd.md
spec/GrumPHP/Task/PhpMdSpec.php
src/GrumPHP/Task/PhpMd.php

Use phpmd's `--exclude` option to exclude directories from the task.

Add exclude option to phpmd

---

README.md
composer.json
doc/tasks.md
doc/tasks/doctrine_orm.md
resources/config/tasks.yml
spec/GrumPHP/Task/DoctrineOrmSpec.php
src/GrumPHP/Task/DoctrineOrm.php

This task makes it possible to validate mappings for Doctrine ORM. By default it'll only validate the mapping and the entity classes, but it's also possible to have it check that the database is in sync. Skipping it by default is personal preference, but I have no problem changing that :)

Add Doctrine ORM task

---

src/GrumPHP/Console/Command/Git/InitCommand.php

Fixes a typo in a comment in `src/GrumPHP/Console/Command/Git/InitCommand.php`. 
> // Some git clients to not automatically create a git hooks folder.
should be:
> // Some git clients do not automatically create a git hooks folder.

Fixes typo in comment.

---

README.md
doc/parameters.md
resources/config/parameters.yml
resources/config/services.yml
resources/config/tasks.yml
spec/GrumPHP/Configuration/GrumPHPSpec.php
spec/GrumPHP/Process/AsyncProcessRunnerSpec.php
spec/GrumPHP/Task/PhpCsFixerSpec.php
spec/GrumPHP/Task/PhpCsFixerV2Spec.php
src/GrumPHP/Configuration/GrumPHP.php
src/GrumPHP/Process/AsyncProcessRunner.php
src/GrumPHP/Task/AbstractPhpCsFixerTask.php

| Branch        | master 
PhpCsFixer takes quite some time when running it on changed files, and this is of course because GrumPHP needs to run one process per file. Symfony's Process component supports running processes asynchronously, so I thought why not give it a spin!
The following benchmark is performed on 23 files with PhpCsFixerV2 as the only task. The former is GrumPHP 0.9.6 and the latter is with this PR. From 10s to 2s is pretty sweet!
```shell
$ time ./vendor/bin/grumphp run
GrumPHP is sniffing your code!
Running task 1/1: PhpCsFixerV2
real    0m10.478s
user    0m1.734s
sys     0m8.297s …
```

Run PhpCsFixer tasks asynchronously

---

doc/tasks.md
doc/tasks/npm_script.md
resources/config/tasks.yml
spec/GrumPHP/Task/NpmScriptSpec.php
src/GrumPHP/Task/NpmScript.php

[FEATURE] add npm_script Task 

---

doc/tasks/phpcs.md
spec/GrumPHP/Collection/FilesCollectionSpec.php
spec/GrumPHP/Task/PhpcsSpec.php
src/GrumPHP/Collection/FilesCollection.php
src/GrumPHP/Task/Phpcs.php

| Q | A |
| --- | --- |
| Branch | master for features and deprecations |
| Bug fix? | no |
| New feature? | yes |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes/no |
| Documented? | yes |
| Fixed tickets | #158 |
This PR add a new `whitelist_patterns`option to `Phpcs` task. It will be used to filter files to be validated.
Example for a Symfony, validate PHP files only in `src/` directory
``` yml
phpcs:
standard: "./vendor/leaphub/phpcs-symfony2-standard/leaphub/phpcs/Symfony2/"
show_warnings: true
whitelist_patterns: ["^src/(.*)"]
triggered_by: [php]
```

Add whitelist_patterns option to Phpcs task

---

src/GrumPHP/Console/Command/Git/InitCommand.php

| Tests pass?   | -
GrumPHP 0.10.0 throw the follow error on `git:init`:
```shell
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to GrumPHP\Util\Filesystem::readFromFileInfo() must be an instance of SplFileInfo, string given
```

Fix uncaught TypeError

---

README.md
doc/tasks.md
doc/tasks/kahlan.md
resources/config/tasks.yml
spec/GrumPHP/Task/KahlanSpec.php
src/GrumPHP/Task/Kahlan.php

| Fixed tickets | #225 
Added support for Kahlan.

Added kahlan support

---

composer.json

| Fixed tickets | #240 
This ticket adds the `ocramius/proxy-manager` dependency to the composer.json file to make sure tha GrumPHP works with t full `symfony/symfony` projects.
More information about the bug can be found in ticket #240.

Make sure that GrumPHP can be used in a full-blown symfony application.

---

README.md
doc/tasks.md
doc/tasks/brunch.md
resources/config/tasks.yml
spec/GrumPHP/Task/BrunchSpec.php
src/GrumPHP/Task/Brunch.php

| Fixed tickets | ~
My PR add support of js building tools Brunch which become more and more popular (such as Gulp and Grunt)

Add brunch support

---

resources/hooks/local/commit-msg
resources/hooks/local/pre-commit
resources/hooks/vagrant/commit-msg
resources/hooks/vagrant/pre-commit

| Tests pass?   | Check Travis
The removed code is the functionally equivalent to `exit $?`. However, this construct is *also* redundant because, according to the documentation, the exit status automatically inherits the status of the last command. Ergo, the entire code is useless.
```
exit: exit [n]
Exit the shell.
Exits the shell with a status of N.  If N is omitted, the exit status
is that of the last command executed.
```

Removed redundant hook exit code

---

doc/tasks/phpcpd.md
spec/GrumPHP/Task/PhpCpdSpec.php
src/GrumPHP/Task/PhpCpd.php

Adds the phpcpd --names-exclude option, this allows a comma-separated list of file names to exclude.
Example:
```
phpcpd:
names_exclude: ['_ide_helper.php']
```

Add phpcpd names-exclude option

---

doc/tasks/php_cs_fixer2.md
spec/Formatter/PhpCsFixerFormatterSpec.php
spec/Task/PhpCsFixerV2Spec.php
src/Formatter/PhpCsFixerFormatter.php
src/Task/PhpCsFixerV2.php

PHP CS Fixer 2 has an option called `--diff` to visualize the diff of all the code violations it found. I added an option to enable the output of this diff when GrumPHP is executed. By default this option is disabled.
One note: i'm not sure why the [`--format=json`](https://github.com/phpro/grumphp/compare/master...jhuet:feature/phpcsfixer2-option-diff?expand=1#diff-5734ec63a7bc6aa3851c2701bfa89c70L66) was forced but it didn't allow the diff output to appear so i removed it.

Add 'diff' option to phpcsfixer2 task

---

doc/tasks/php_cs_fixer2.md

| Fixed tickets | #281
Due to a missing hint on escaping the new rules grumphp breaks the php_cs_fixer v2. 
More details on this here:
https://github.com/phpro/grumphp/issues/281
Tested and working local as well as prod for me

Updated php_cs_fixer v2 doc @@ escaping

---

doc/tasks/php_cs_fixer2.md
spec/Task/PhpCsFixerV2Spec.php
src/Task/PhpCsFixerV2.php

| Fixed tickets | #284
This PR adds "triggered_by" option to the phpcsfixer2 task as described in #284.

Triggered by option for phpcsfixer2 task

---

.github/issue_template.md

*Branch* doesn't make sense for issues. I have replaced it with the version because we might want to know which version of the program the user is using instead.

Changed issue template "branch" to "version"

---

src/Task/JsonLint.php
src/Task/PhpParser.php
src/Task/Phpcs.php
src/Task/XmlLint.php
src/Task/YamlLint.php

Removes field shadowing from tasks and replaces them with `@property` annotations to facilitate code completion for the derived type of the inherited field.

Remove task field shadowing

---

composer.json
doc/tasks/php_cs_fixer2.md
spec/Task/PhpCsFixerV2Spec.php
src/Task/PhpCsFixerV2.php

| Fixed tickets | #288
Adds JSON rule support for PHP-CS-Fixer v2.1. To take advantage of this, the rules should be specified as a map instead of a list in the YAML configuration. However, to maintain backwards compatibility, list style is still supported, in which case rules will be comma-delimited as before.

Added JSON rules support for PHP-CS-Fixer v2.1.

---

spec/Task/Php7ccSpec.php
src/Task/Php7cc.php

| Fixed tickets | #307 #296 
@jyggen: Something went wrong while rebasing and I do net have the permissions anymore to push the fix to your branch. I've added your commit in this PR.

Only fail when errors are raised

---

doc/tasks/phpunit.md
spec/Task/PhpunitSpec.php
src/Task/Phpunit.php

| Fixed tickets | #297 
Add a testsuite option to the phpunit task

Phpunit suite

---

README.md
appveyor.yml
spec/Runner/TaskRunnerSpec.php
spec/Task/Php7ccSpec.php
src/Configuration/ContainerFactory.php
src/Event/Subscriber/ProgressSubscriber.php
src/Event/TaskEvents.php
src/Process/ProcessBuilder.php
src/Runner/TaskResult.php
src/Runner/TaskRunner.php
src/Task/JsonLint.php
src/Task/Php7cc.php
src/Task/Phpcs.php
src/Task/XmlLint.php
src/Task/YamlLint.php

It would be nice to get an overview of which tasks passed and failed while GrumPHP is executing. Tasks that complete successfully tend to not output anything which isn't very helpful. Now tasks will output either a green ✔ or red ✘ in the progress summary.

Added coloured ballot marks for completed tasks.

---

README.md
doc/events.md
doc/parameters.md
resources/config/parameters.yml
spec/Console/Helper/TaskRunnerHelperSpec.php
spec/Runner/TaskRunnerContextSpec.php
src/Configuration/GrumPHP.php
src/Console/Application.php
src/Console/Command/Git/PreCommitCommand.php
src/Console/Command/RunCommand.php
src/Console/Helper/PathsHelper.php
src/Console/Helper/TaskRunnerHelper.php
src/Runner/TaskRunnerContext.php

| Fixed tickets | #286
Adds a parameter to configure whether to show the Git commit hook circumvention tip when a task fails.
One of the phpspec tests currently fails but I don't know phpspec so I don't understand why. Since I do not know phpspec I haven't written any new tests to cover this new feature; help wanted!
>----  broken examples
>
>        GrumPHP\Runner\TaskRunnerContext
>  40  ! knows to skip the success message
no skipSuccessOutput([array:0]) matcher found for
[obj:GrumPHP\Runner\TaskRunnerContext].
I had difficulty even just testing this new feature manually. Although I can normally install GrumPHP, it …

Added hide_circumvention_tip parameter.

---

resources/config/tasks.yml

Seems like the `git_conflict` task isn't registered.

Add missing configuration for git_conflict

---

spec/Formatter/PhpCsFixerFormatterSpec.php
src/Formatter/PhpCsFixerFormatter.php

Adds spaces between fixer names for PHP-CS-Fixer task to make list of fixers applied to a file more readable. This is consistent with the format output by the tool normally.

Added spaces between PHP-CS-Fixer formatter fixers

---

doc/tasks/git_commit_message.md
src/Task/Git/CommitMessage.php

When a commit message failed we used to see:
>The commit message does not match the rule: /JIRA-\d+/
Now we see:
>Rule not matched: "Must contain JIRA issue number" /JIRA-\d+/
Seems good 👍

Added support for a commit message rule names displayed in failure output

---

README.md
composer.json
doc/tasks.md
doc/tasks/phpstan.md
resources/config/tasks.yml
spec/Task/PhpStanSpec.php
src/Task/PhpStan.php

| Fixed tickets | #248
PHPStan task. When in `GitPreCommitContext` it'll filter the result and only report errors for files that are actually being commited. 
Currently it parses the results table with regexp (since PHPStan don't support different output formats), which have worked flawlessly for me for a while but probably is a bit too hacky to be in an "official" GrumPHP task. 
Luckily there's a PR in progress (https://github.com/phpstan/phpstan/issues/132), so either we wait for it to be merged and rewrite some code or just remove the filtering all together if we rather always report all files :)

Add PHPStan task

---

README.md
doc/tasks.md
doc/tasks/deptrac.md
resources/config/tasks.yml
spec/Task/DeptracSpec.php
src/Task/Deptrac.php

| Fixed tickets | #278
The deptrac tool should be installed manually as recommended by their documentation.

Feature/deptrac 

---

doc/tasks/phpversion.md

InvalidOptionsException: The option "project" is expected to be of type "null" or "string", but is of type "double" by the docs.

Updated phpversion.md

---

composer.json

| Documented?   | yes/no
Magento 2.1 project currently requires `monolog/monolog` version `1.16.0`, whilst grumphp requires version `~1.17`. This shouldn't really break functionality it only should expand compatibility a bit more. [See release notes of `monolog/monolog` version 1.17.0](https://github.com/Seldaek/monolog/releases/tag/1.17.0).

Lower monolog/monolog version constraint for Magento 2 project compatibility

---

composer.json
doc/tasks.md
doc/tasks/phpmnd.md
resources/config/tasks.yml
spec/Task/PhpMndSpec.php
src/Task/PhpMnd.php

This PR adds support for [PHP Magic Number Detector](https://github.com/povils/phpmnd) (PHPMND).
> `phpmnd` is a tool that **helps** you detect magic numbers in PHP code.
>
> **What is Magic Number?**
>Magic number is a numeric literal that is not defined as a constant that may change at a later stage, but that can be therefore hard to update. It is a bad programming practice of using numbers directly in source code without explanation. In most cases this makes programs harder to read, understand, and maintain.

Add PhpMnd task

---

.travis.yml
spec/Event/Subscriber/ProgressSubscriberSpec.php
src/Task/PhpStan.php

Symfony 3.3.0 makes the ProgressBar final. This causes all mocked ProgressBar objects to crash in phpspec.
Additional info:  https://github.com/symfony/symfony/pull/20487

Fix symfony progressbar issues

---

doc/tasks/git_commit_message.md
spec/Task/Git/CommitMessageSpec.php
src/Task/Git/CommitMessage.php

These are the same enforcements introduced by the tasks in #319, but built into the existing `git_commit_message` task instead (as discussed [here](https://github.com/phpro/grumphp/pull/319#issuecomment-284313781)).
While I agree that it's probably a good idea to drop `case_insensitive`, `multiline` and `additional_modifiers` and let the matchers define their desired modifiers themselves, that is a breaking change and not really in the scope of this PR.

Add various enforcements to git_commit_message

---

spec/Formatter/GitBlacklistFormatterSpec.php
src/Formatter/GitBlacklistFormatter.php

| Fixed tickets | #293 
For blacklisted keywords on lines longer then 80 characters the output
was not well formatted. The wrong starting position was used
within the mb_substr method, a negative one which resulted that the substr started
at the end of the error message. This has been
resolved by making sure the starting position will not be negative.
The outcome is now the following:
```
You have blacklisted keywords in your commit:
t.php
1:20: 8:    private $' . $this->callSo
```
The last number is the actual line number where the keyword is in.

Blacklisted keywords on lines bigger then 80 chars will now display their error message correctly.

---

src/Task/PhpMnd.php

Seems like the documentation for phpmnd ~is~ [was](https://github.com/povils/phpmnd/pull/58) wrong and the option for excluding files is actually named `exclude-file` (_gasp!_).
I chose to keep the name `exclude_name` for GrumPHP though to avoid unnecessary BC break.

Fix exclude_name parameter for phpmnd task

---

src/Task/PhpMnd.php

Another fix for the phpmnd task. Unlike some of the other options, the three for excluding files wants one argument per file instead of a comma-separated list (so `--exclude=a.php --exclude=b.php` instead of `--exclude=a.php,b.php`).

Use argument arrays for phpmnd's exclude options

---

src/Linter/Xml/XmlLinter.php

The currently code isn't so friendly to relative paths since it always adds a `DIRECTORY_SEPARATOR`.
For example if I have `phpunit.xml` in the root of the project and add `vendor/phpunit/phpunit/phpunit.xsd` as a scheme in it, the linter would end up resolving its path as `/vendor/phpunit/phpunit/phpunit.xsd`. This is due to `$xmlFile->getPath()` returning an empty string, and thus the enforced `DIRECTORY_SEPARATOR` turns it into an absolute path.
This change will make sure that `DIRECTORY_SEPARATOR` is only added when the file actually has a path, and the `rtrim()` is there to make sure we don't …

Only add DIRECTORY_SEPARATOR if needed

---

README.md
composer.json
doc/tasks.md
doc/tasks/composer_require_checker.md
resources/config/tasks.yml
spec/Collection/FilesCollectionSpec.php
spec/Task/ComposerRequireCheckerSpec.php
src/Collection/FilesCollection.php
src/Task/ComposerRequireChecker.php

Adds support for [composer-require-checker](https://github.com/maglnet/ComposerRequireChecker).
> A CLI tool to analyze composer dependencies and verify that no unknown symbols are used in the sources of a package. This will prevent you from using "soft" dependencies that are not defined within your `composer.json` require section.

Add task for composer-require-checker

---

src/Task/CloverCoverage.php

Added a skip Task when the total number of elements in the clover.xml file is zero.
| Branch        | master 
| Documented?   | yes/no

CloverCoverageTask; fixing devided by 0 warning 

---

README.md
composer.json
doc/tasks.md
doc/tasks/infection.md
resources/config/tasks.yml
spec/Collection/ProcessArgumentsCollectionSpec.php
spec/Task/InfectionSpec.php
src/Collection/ProcessArgumentsCollection.php
src/Task/Infection.php

Add infection task

---

README.md

Update the documentation with the correct minimum required PHP version.
Since 31/05/2017, grumphp no longer supports HHVM.

Fix minimum PHP version and compatibility

---

doc/tasks/yamllint.md
spec/Task/YamlLintSpec.php
src/Linter/Yaml/YamlLinter.php
src/Task/YamlLint.php
test/Linter/Yaml/YamlLinterTest.php
test/fixtures/linters/yaml/constant-support.yml
test/fixtures/linters/yaml/tags-support.yml

| Fixed tickets | N/A
In Symfont 3.2 and 3.3, the Yaml component added support for PHP constants and custom tags.
Currently when using constants or custom tags in a Yaml file, the yamllint task fails because the syntax is invalid (and the necessary flags is not passed through).
This PR adds 2 new options to the yamllint task: `parse_constant` & `parse_custom_tags`. These options default to false to keep current behaviour. If they are set to `true`, then the required flags is passed through to the Yaml::parse method so that the task doesn't fail.

Add parse_constant and parse_custom_tags options to yamllint task

---

src/Console/Helper/TaskRunnerHelper.php

Currently things that uses `$this->output` (like `✔` and `✘`) writes to _stdout_ while everything that utilizes ProgressBar usually writes to _stderr_. This PR simply replicates how ProgressBar handles output internally to make output a bit more consistent.

Write task progress to error output

---

composer.json

| Bug fix?      | kind of
This is a must have for : 
- Sf4 support (#428), as without it composer will refuse to install v4
- PHP7 support (#434), as without it we will have ugly crashes on PHP7 - bug was fixed on gitlib side and just released

bump gitlib requirement

---

resources/config/services.yml

| New feature?  |no
When you install a fresh copy of grumphp into a symfony 4 app, and run grumphp run with super verbosity (-vvv) you'll get the next error:
`[Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]
The "grumphp.logger" service or alias has been removed or inlined when the container was compiled. You should either make it public, or stop using t
he container directly and use dependency injection instead.`

Fix: changing visibility of grumphp.logger service/alias to public

---

doc/tasks/phpcs.md
spec/Task/PhpcsSpec.php
src/Task/Phpcs.php

| Deprecations? | yes (show_warnings option is deprecated)
| Fixed tickets | #449
Added the ability to pass error severities, show_warnings option is deprecated since it was using the task parameter --warning-severity.

Added severity levels to phpcs task

---

src/Configuration/Compiler/TaskCompilerPass.php

| Branch        | master, 0.13.1
On install of grumphp without an grumphp.yml file I get this Warning:
Warning: array_key_exists() expects parameter 2 to be array, null given in /var/www/secure_login/vendor/phpro/grumphp/src/Configuration/Compiler/TaskCompilerPass.php on line 37
Wit my Proposed Changes this warning will be removed.

Remove Warning for array_key_exists

---

spec/Process/ProcessBuilderSpec.php
src/Console/Command/Git/InitCommand.php
src/Process/ProcessBuilder.php

| Fixed tickets | #458, #462, #447
This bug was introduced in version 0.13 : before we used to force the git hook command to be unix styled. 
(reference: https://github.com/phpro/grumphp/commit/415fd1a9c70f5905326f0651ac5009a70d42441e#diff-aed6b638f2d7de8614c3516d7939c1a0L135 )

Force git hooks to contain unix styled commands

---

doc/tasks/composer_require_checker.md
spec/Task/ComposerRequireCheckerSpec.php
src/Task/ComposerRequireChecker.php

This adds an option to enable `--ignore-parse-errors`, which is available in ComposerRequireChecker since 0.2.0.
One thing to note is that ~the world will crash and burn~ ComposerRequireChecker will throw a hissy fit if you have <0.2.0 installed and enable this. I think pointing this out in the docs should be good enough since the option is opt-in. We could always go down the route of version detection, but `composer-require-checker --version` identifies itself as `0.1.1-dev` on 0.2.0 :(

Add ignore_parse_errors option to ComposerRequireChecker

---

composer.json
resources/config/services.yml
src/Configuration/ContainerFactory.php
src/Console/Application.php
src/IO/ConsoleIO.php

| Deprecations? |  no
As the title says, remove the proxy manager.
@veewee (and everyone else), please leave your remaks below.

Remove proxy manager

---

doc/tasks/phpcsfixer2.md
spec/Collection/ProcessArgumentsCollectionSpec.php
spec/Task/PhpCsFixerV2Spec.php
src/Collection/ProcessArgumentsCollection.php
src/Task/PhpCsFixerV2.php

| Fixed tickets | #469
Existed non-null default values of "allow_risky" and "using_cache" options were overriding the values from .php_cs config.
The current behavior is that if these options are not specified, the values will be taken from the .php_cs config.

Changed phpcsfixer2 default options

---

resources/hooks/local/commit-msg
resources/hooks/local/pre-commit
resources/hooks/vagrant/commit-msg
resources/hooks/vagrant/pre-commit

| Fixed tickets | #164
If anyone has git settings like `color.ui=always` or `diff.mnemonicprefix=true` (and maybe using a pager) this may break diff output like we see in #164. In order to not make users change their git settings I propose this PR that standardizes git settings to some extent upon starting `git diff`.

Made "git diff" behave more predictably

---

spec/Task/PhpCpdSpec.php
src/Task/PhpCpd.php

Previous formatting of the option did not match the "phpcpd" interface.
| Fixed tickets | #475
Changed `phpcpd` "names_exclude" option formatting so that it matches the `phpcpd` interface.

Changed phpcpd "names_exclude" option

---

src/Console/Helper/PathsHelper.php

git supports using a custom path for the `.git` directory. When used, `.git` is a file containing `gitdir: <path>` to point at the real directory.
Currently grumphp does not support this, because the path used to install the git hooks is incorrect (there obviously can't be a `.git/hooks` in this case). This also can't be worked around with the config param `git-dir` (which by the way is badly named) because the path used will always end with `.git/hooks`, but the custom directory may be named differently (not `.git`).
This PR adds support for custom repository paths by reading `.git` if it's a file …

Add support for custom location of .git directory

---

src/Console/Command/Git/CommitMsgCommand.php

When grumphp is used with a `.git` dir in a non-standard location the `commit-msg` hook may look for the `.git/COMMIT_EDITMSG` file in the wrong location.
This PR prefixes the path with `git_dir` configured in `grumphp.yml` if it's a relative path, so the correct path is used in all cases.
Note: The path supplied to the hook by git may be absolute. In this case there is no need to fix it. This happens when grumphp is used inside a git submodule.

Use correct path to .git/COMMIT_EDITMSG when using non-standard .git dir location

---

doc/tasks/file_size.md
spec/Task/FileSizeSpec.php
src/Task/FileSize.php

Add ignore patterns for File size task

---

spec/Collection/ProcessArgumentsCollectionSpec.php
src/Collection/ProcessArgumentsCollection.php
src/Task/Phpcs.php

| Fixed tickets | 466
Related to #466, I added \GrumPHP\Collection\ProcessArgumentsCollection::addOptionalIntegerArgument() method and changed the calls in the phpcs task to use this.

Added addOptionalIntegerArgument to fix issue with phpcs warning_severity

---

doc/tasks/phpcpd.md
spec/Task/PhpCpdSpec.php
src/Task/PhpCpd.php

| Fixed tickets | #477
Added the phpcpd "paths_exclude" option, which corresponds to the `--regexps-exclude` console option of phpcpd.

Add phpcpd "paths_exclude" option

---

doc/tasks/git_blacklist.md
spec/Task/Git/BlacklistSpec.php
src/Task/Git/Blacklist.php

As for https://github.com/phpro/grumphp/pull/160 this PR add a new `whitelist_patterns`option to `GitBlacklist` task. It will be used to filter files to be validated.
Example for a Symfony, validate PHP files only in `src/` directory
``` yml
git_blacklist:
whitelist_patterns: ["^src/(.*)"]
```

Add whitelist_patterns to GitBlacklist

---

doc/tasks/phpmd.md
spec/Task/PhpMdSpec.php
src/Task/PhpMd.php

As for https://github.com/phpro/grumphp/pull/160 this PR add a new `whitelist_patterns`option to `PhpMd` task. It will be used to filter files to be validated.
Example for a Symfony, validate PHP files only in `src/` directory
``` yml
phpmd:
whitelist_patterns: ["^src/(.*)"]
```

Add whitelist_patterns option to PhpMd task

---

README.md
composer.json
doc/tasks.md
doc/tasks/progpilot.md
resources/config/tasks.yml
spec/Task/ProgpilotSpec.php
src/Task/Progpilot.php

Add Progpilot task

---

src/Parser/Php/Visitor/DeclareStrictTypesVisitor.php

| Fixed tickets | #508 
As described in #508 the visitor that checks the `declare(strict_types = 1);` directive currently only works with PhpParser 3 and below, and always fails on PhpParser 4.
This PR makes sure it is compatible with PhpParser 4 and above.

Make detection of strict types compatible with PhpParser 4.

---

composer.json
doc/tasks/phan.md

`etsy/phan` has been deprecated. Please use `phan/phan`.

Correct package-name of phan

---

src/Console/Command/ConfigureCommand.php

| Fixed tickets | #516
Fixes #516 by not running the tasks question in non-interactive mode.

Only run question helper in interactive mode

---

doc/tasks/yamllint.md
spec/Task/YamlLintSpec.php
src/Task/YamlLint.php

| Fixed tickets | [#527](https://github.com/phpro/grumphp/issues/527)
As for PRs : 
- [#160](https://github.com/phpro/grumphp/pull/160) 
- [#494](https://github.com/phpro/grumphp/pull/494) 
- [#496](https://github.com/phpro/grumphp/pull/496) 
- [#498](https://github.com/phpro/grumphp/pull/498) 
This PR add a new whitelist_patternsoption to Yamllint task. It will be used to filter files to be validated.
Example for a Symfony, validate PHP files only in src/ directory
``` yml
yamllint:
ignore_patterns: []
object_support: false
exception_on_invalid_type: false
parse_constant: false …
```

Allow to filter with a regex pattern with the addition of whitelist pattern option to Yaml Lint task

---

doc/tasks/git_commit_message.md
src/Task/Git/CommitMessage.php

| Deprecations? |  no
| Fixed tickets | 532
The PR adds a simple check that allows users to set the max_subject_width and max_body_width variables from the git_commit_msg task to 0. Like this we allow them to disable the check altogether.

Issue #532: Allow to set max_subject_width and max_body_width to 0

---

doc/tasks/phpcs.md
src/Task/Phpcs.php

| Fixed tickets | none, direct PR
Adds two more options for the `phpcs` task, `report` and `report_width`which lets the final user choose values for these options that will be passed downwards to `phpcs`.

Add more options for the 'phpcs' task, in particular the 'report' one.

---

src/Console/Helper/PathsHelper.php

In the rare instance that a person has an absolute path in their .git file, grumphp fails to handle the issue.
This one-liner ensures that the path is always parsed as relative first.

Fix issue when .git file has absolute path

---

doc/parameters.md
src/Configuration/GrumPHP.php

| Fixed tickets | None
To disable all banners set ascii to `~`:
```yaml
parameters:
ascii: ~
```

feat: Add option to disable all banners by setting ascii to null

---

doc/parameters.md
resources/config/parameters.yml
spec/Configuration/GrumPHPSpec.php
spec/Console/Helper/TaskRunnerHelperSpec.php
src/Configuration/GrumPHP.php
src/Console/Helper/TaskRunnerHelper.php

Adds the ability to set additional information to be displayed after tasks have finished. Is useful for displaying resources ie: documentation urls
**additional_info**
*Default: null*
This parameter will display additional information at the end of a `success` *or* `error` task.
```yaml
parameters:
additional_info: "\nTo get full documentation for the project\nVisit https://docs.example.com\n"
```
*Example Result:*
```
GrumPHP is sniffing your code!
Running task 1/1: Phpcs... ✔
To get full documentation for the project
Visit https://docs.example.com
```

feat: Add additional info parameter

---

src/Configuration/GrumPHP.php
src/Console/Helper/PathsHelper.php

| Branch        | grumpy-seventies
When running the `composer install` from a new checkout of this repo `git clone grumphp` there are two errors. It looks like its expecting null values and I'm sure this wont affect the usage in projects but will affect those contributing to this repo. 
Solution is nullable types in 7.1 but this should fix it for PHP7

Php7 issues

---

test/fixtures/linters/xml/xsd-url-invalid.xml
test/fixtures/linters/xml/xsd-url-valid.xml

Currently tests are failing based on a XSD that isn't available anymore.
I've moved them to a gist which I won't remove.

Host our own version of the symfony XSDs

---

composer.json
spec/Task/PhpLintSpec.php
src/Task/PhpLint.php

| Branch        | gsomoza/grumphp:phplint-input-stream
| Documented?   | not needed
| Fixed tickets | none, but see #524
See #524: this task allows phplint to work with large number of files.

Allow PHPLint to handle large number of files

---

.travis.yml

Composer's default cache directory has changed, and now the travis.yml reflects that.
| Fixed tickets | None
This patch is a trivial fix to GrumPHP's travis configuration and shouldn't affect anything otherwise.

Fix travis composer cache

---

doc/tasks/phplint.md
spec/Task/PhpLintSpec.php
src/Task/PhpLint.php

PHP Lint: allow short open tags

---

doc/tasks/phpstan.md
spec/Task/PhpStanSpec.php
src/Task/PhpStan.php

This adds the option for PhpStan to set a memory-limit for the analyser.

Add memory-limit parameter to PhpStan

---

src/Console/Command/ConfigureCommand.php

| Fixed tickets | None
`$path` should be a string and not a boolean. Not sure how this isn't breaking for anyone else.

Fixes return type of `ConfigureCommand::pathValidator`

---

composer.json
doc/tasks.md
doc/tasks/ecs.md
resources/config/tasks.yml
spec/Task/EcsSpec.php
src/Task/Ecs.php

Add EasyCodingStandard task for use for exemple :
- https://github.com/Symplify/EasyCodingStandard
- https://github.com/SyliusLabs/CodingStandard
- ...

add Ecs (EasyCodingStandard) Task

---

src/Console/Command/Git/CommitMsgCommand.php
src/Console/Command/Git/DeInitCommand.php
src/Console/Command/Git/InitCommand.php
src/Console/Command/Git/PreCommitCommand.php

This PR adds descriptions to the commands with the `git:` prefix like `git:init`. The descriptions should help users to understand what these commands do and to figure out how to initialize / re-initialize their GrumPHP installation.

Add descriptions to the git:* commands

---

src/Collection/TaskResultCollection.php
src/Console/Command/ConfigureCommand.php
src/Console/Command/Git/PreCommitCommand.php
src/Console/Command/RunCommand.php
src/Util/Str.php

String
Added type hinting where missing. 
TaskResultCollection: only returns int
ConfigureCommand: return is string, which is the parameter, therefore parameter should be string.
PreCommitCommand: never returns void
RunCommand: never returns void
Str: doc says string, should be string

Adds PHP7 type hinting where missing

---

doc/tasks/phpcs.md
spec/Task/PhpcsSpec.php
src/Task/Phpcs.php

Add the exclude option to the phpcs-task: https://github.com/squizlabs/PHP_CodeSniffer/wiki/Advanced-Usage#limiting-results-to-specific-sniffs

Implement the Phpcs exclude option

---

README.md
composer.json
doc/tasks.md
doc/tasks/composer_normalize.md
resources/config/tasks.yml
spec/Task/ComposerNormalizeSpec.php
src/Task/ComposerNormalize.php

Add task composer normalize

---

.gitignore
.travis.yml
appveyor.yml
composer.json
doc/tasks/paratest.md
grumphp.yml.dist
spec/Process/ProcessBuilderSpec.php
spec/Process/ProcessFactorySpec.php
spec/Runner/TaskRunnerSpec.php
spec/Task/ParatestSpec.php
src/Task/Paratest.php
test/Bootstrap.php
test/E2E/AbstractE2ETestCase.php
test/Unit/Linter/Json/JsonLinterTest.php
test/Unit/Linter/Xml/XmlLinterTest.php
test/Unit/Linter/Yaml/YamlLinterTest.php
test/fixtures/e2e/tasks/ValidatePathsTask.php
test/fixtures/linters/yaml/constant-support.yml

This PR will bump phpunit and phpspec to higher versions.
It also includes paratest for faster e2e testing.
Finally, the config of appveyor is optimized and additional php versions are added.

Improve e2e time on appveyor

---

src/Task/PhpLint.php

There was a bug when you try to commit (pre-hook) some non-php files.
You receive the PHP Parallel Lint usage error every time. With this it
will be marked as "passed" when no files are available to pass trough
the linter.

Fixed a bug when phplint is active and only non-php files are commited

---

doc/tasks/composer_normalize.md

Adding missing composer information for Composer Normalize on Docs

Add missing composer information for Composer Normalize on Docs

---

composer.json
doc/tasks/twigcs.md
src/Task/TwigCs.php

Updated TwigCs from allocine/twigcs to friendsoftwig/twigcs when [allocine/twigcs is abandoned and no longer maintained](https://packagist.org/packages/allocine/twigcs).

TwigCs - allocine/twigcs is abandoned. Changed to friendsoftwig/twigcs

---

doc/tasks/phpstan.md

`memory_limit` must be `null` or `string`.
| Bug fix?      | yes/no
| New feature?  | yes/no
| BC breaks?    | yes/no
| Deprecations? | yes/no
| Documented?   | yes/no

Fix memory_limit type.

---

.gitignore

| Bug fix?      | yes (?)
Because of the .gitignore in this project, we cannot commit the executable for grumphp to our repository. We would like to do that, but afaik there is no way to overrule that without changing the .gitignore file itself. This PR does exactly that.
Note that not committing our vendor directory is currently not an option.

adjust the gitignore so the bin directory gets included in the repo

---

doc/installation/exotic.md
resources/config/services.yml
resources/config/util.yml
src/Configuration/Configurator/ExecutableFinderConfigurator.php
src/Configuration/ContainerFactory.php
src/Util/ComposerFile.php

| Fixed tickets | #671, #677
This PR:
- Moves bin-dir prepending to PATH outside the ComposerFile logic and runs it when loading the Symfony exectuable finder. This fixes a possible issue when a bin dir is defined with env variables that is different from the one in composer.
- Adds documentation on how to support multiple bin dirs.
- Adds `.phar` as a valid suffix so that those executables can also be detected.

Improve exectuable locator

---

.gitattributes

| Branch        | master 
| New feature?  | Yes
| Fixed tickets | None
This makes the composer installers smaller as the test are not shipped

Ignore files from zip export

---

src/Formatter/PhpcsFormatter.php

| Fixed tickets | #662 
5 months ago a commit changes how PHPCS ends the json report by adding  a new line at the end. You can see here: https://github.com/squizlabs/PHP_CodeSniffer/blob/master/src/Reports/Json.php#L101
This messes up the PhpcsFormatter because the last "\n" that finds is the new PHP_EOL that is added to de report. 
With this fix it won't print the json report and will prompt for autofixing like before.
No

Fix phpcs formatter

---

doc/tasks/deptrac.md
src/Task/Deptrac.php

By default, `addOptionalArgument` in `ProcessArgumentsCollection` discards an argument when the value evaluates to false.
This results in the absence of the option in the final process command.
In many cases, the absence of an option means false, but in the case of Deptrac's `--formatter-graphviz-display` it means true.
The use of `addOptionalArgument` will never allow false, so unsetting this option in Deptrac is impossible. 
In `Deptrac.php` all options are always present, so adding it just by default with `add` will fix this.
**Edit:**
Because the default value …

Fix: do not display graphiz when argument is set false

---

src/Util/Filesystem.php

| Documented?   | N/a
| Fixed tickets | N/a
We check that the file exists, but if for whatever reason we cant
make a realpath out of it, or if we have another process that deletes
this in the mean time, then we could have a type error.
By retrieving the real path, and then checking the error condition
we  remove the ability for a type error to occur here.
We dont change the fact that the file in question can still be
deleted in the mean time, as thats not within the scope of this method.

Rework realpath logic to remove the possibility of a type error

---

src/Task/Git/CommitMessage.php
src/Task/PhpLint.php

PHP 7.4 emits a deprecation warning when calling implode in reverse order from the documented order of arguments eg. implode($pieces, $glue): 
https://wiki.php.net/rfc/deprecations_php_7_4#implode_parameter_order_mix
For historical reasons, the implode() function supports passing the $glue and $pieces parameters in either order, so this change will not create any BC break:
https://www.php.net/manual/en/function.implode.php

Swap implode function parameters to fix php 7.4 deprecation

---

spec/Task/Git/CommitMessageSpec.php
src/Task/Git/CommitMessage.php

| Fixed tickets | N/A
it's not possible to pass the task "commit-message" when we use :
`git commit --fixup ...`
This PR Fix that adding some rules on the Regex

fix(commit-message): CheckTypeScope with a special prefix

---

doc/tasks/phpcpd.md
src/Task/PhpCpd.php

| Branch        | `support-phpcs-multiple-dirs`
| Bug fix?      | yes/**no**
| New feature?  | **yes**/no
| BC breaks?    | yes/**no**
| Deprecations? | yes/**no**
| Documented?   | **yes**/no
| Fixed tickets | #696
Phpcpd allows users to pass multiple directories to the command. The tool will then check for duplicated code in those directories.
Grumphp doesn't take advantage of this - instead, users can only pass a single string for the directory.
This PR changes the string into an array, and updates the processing and docs accordingly.

Pass array of directories to phpcpd

---

doc/tasks/phpcs.md

Since FriendsOfPHP/PHP-CS-Fixer#4502 will soon be merged, the documentation should mention this change too in the future
This PR just completes the list of supported standards for phpcs

Adding PSR12 to documentation

---

doc/tasks/npm_script.md
spec/Task/NpmScriptSpec.php
src/Task/NpmScript.php

This PR adds a `silent` argument to the npm task which appends `--silent` to the script that will be ran. This suppresses `npm ERR!` messages from showing.

Add silent argument to npm task

---

src/Process/ProcessFactory.php

Fixes #706.
However, I think it breaks use with Symfony Process 4.x and 3.x which according to the `composer.json` are still supported. I didn't see anything in Symfony Process that allows us to determine which version is currently running. Have you solved this issue before?
BTW, a comment in the Symfony Process constructor says arrays started being accepted as the first argument in Symfony 4.2.

Remove Old Compatibility Layer for Pre-5.x Symfony Process

---

doc/tasks/phpcs.md
src/Task/Phpcs.php

| Bug fix?      | yes (missing phpcs functionality)
| Fixed tickets | #715
I have given a detailed description in #715.

Use triggered_by option for extensions argument for phpcs. Fixes #715.

---

spec/Task/Git/CommitMessageSpec.php
src/Task/Git/CommitMessage.php

| Fixed tickets | #656 
This commit looks for a known marker in the git commit message when using `git --verbose` when the marker is seen it will ignore all lines after that (it will assume them to be comments).
The specs will test that long commit messages still fails above the marker.

fix: should not fail on long body when using git --verbose

---

README.md

The list of tasks is someting that can be outdated (#725). It's duplicated documentation since all tasks have separated documentation files (/doc/tasks/*.md) and each task is already listed in (/doc/tasks.md).

Remove tasks from readme

---

src/Configuration/Compiler/TaskCompilerPass.php

With the taskId as key the label config gets overwriten by the last configuration
Test Setup:
```
tasks:
shell:
scripts:
- ['-c', 'echo', 'Running Task']
shell_phpcs:
metadata:
label: 'Test'
task: shell
scripts:
- ['-c', 'echo', 'test1']
shell_phpmd:
metadata:
label: 'Hello'
task: shell
scripts:
- ['-c', 'echo', 'test1']
```
Output with taskId: 
```
Running task 1/3: Hello... ✔
Running task 2/3: Hello... ✔
Running task 3/3: Hello... ✔
```
Output with taskName: 
```
Running task 1/3: shell... ✔
Running task 2/3: Test... ✔
Running task 3/3: Hello... ✔
```

Fixed label output

---

grumphp.yml.dist

I deleted the bin_dir and git_dir options from the grumphp.yml.dist as they are no longer used.

Removed unused parameters for grumphp.yml.dist

---

doc/tasks/psalm.md
spec/Locator/ExternalCommandSpec.php
src/Locator/ExternalCommand.php

Not every project allows to install psalm as a dependency.
I could not run the psalm task as I had installed the phar version.
I added support for the phar version of psalm in this PR by adding a new config option.

Added support for phar executables

---

src/Task/AbstractLinterTask.php
src/Task/AbstractParserTask.php

If you add phpparser to your tasks but forget to require php-parser in composer the exception thrown in the constructer hits an undefined getName() method. This could be added in the interface or in this abstract class, I chose the later.
**constructor code**
```
public function __construct(ParserInterface $parser)
{
$this->configuration = new EmptyTaskConfig();
$this->parser = $parser;
if (!$parser->isInstalled()) {
throw new RuntimeException(
sprintf('The %s can\'t run on your system. Please install all dependencies.', $this->getName())
);
}
}
````

Fixed exception message in constructor

---

doc/tasks/twigcs.md
src/Task/TwigCs.php
test/Unit/Task/TwigCsTest.php

| Fixed tickets | https://github.com/phpro/grumphp/pull/657#issuecomment-539366301
Add exclude option on TwigCs after add it in https://github.com/friendsoftwig/twigcs/pull/81
I think we have to wait for the next Tag on friendsoftwig/twigcs before we merge this PR, because the feature is only on Master branch currently :wink:  (See https://github.com/friendsoftwig/twigcs/issues/82)

twigcs exclude subfolders

---

doc/tasks/phpcsfixer2.md

Add a footnote that warns about setting the `config_contains_finder` to `true` (or leaving the default which is `true`) when using php-cs-fixer2 task on a lot of files. 
See https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/4745 : on a docker+osx environment, leaving the intersection with the list of files given by grumphp can go into a timeout, if configured (otherwise it runs for a long time, gave up after 2min).
We didn't have this problem because we were making our own php_cs config for grumphp, which had a finder... but with only the result of the `git diff --staged` command (and a few pipes and greps). Removing …

Add a footnote on using finder config in intersection mode

---

src/Console/Command/ConfigureCommand.php

| Branch        | 0.19.0
When `composer install` does not find a grumphp.yml file, the configuration wizard is started.
Right after that, the `grumphp git:init` command is triggerd.
Since the content of the GrumPHP file still contains 'parameters', you get this error:
```
PHP Fatal error:  Uncaught GrumPHP\Exception\DeprecatedException: Direct configuration of parameter tasks is not allowed anymore.
Please rename the `parameters` section in your grumphp.yaml file to `grumphp`.
More info: https://github.com/phpro/grumphp/releases/tag/v0.19.0
```

Fix invalid config generation

---

src/Fixer/FixerUpper.php

Fix double space between "can" and "fix": "I can__fix some stuff"

Typo: Remove extra space in output text of FixerUpper

---

doc/tasks/paratest.md
src/Task/Paratest.php
test/Unit/Task/ParatestTest.php

Now for paratest task grumphp support only `--coverage-html` and `--coverage-xml` agrument. I added support also for `--coverage-clover` and `--coverage-php`.
Currently paratest don't support generating clover coverage base on phpunit logging configuration, so without that change we can't use paratet to generate correct raport to `clover_coverage` task.

paratest: Add support for '--coverage-clover' and '--coverage-php'

---

doc/tasks.md
doc/tasks/eslint.md
resources/config/formatter.yml
resources/config/tasks.yml
spec/Formatter/ESLintFormatterSpec.php
src/Formatter/ESLintFormatter.php
src/Task/ESLint.php
test/Unit/Task/ESLintTest.php

Add [ESLint](https://eslint.org/) task for javascript code static analysis (code quality and coding style). 
As a good amount of php projects also have some javascript frontend, it's handy to lint your JS during pre-commit as well.
Example task run:
```
$ git commit
GrumPHP detected a pre-commit command.
GrumPHP is sniffing your code!
Running task 1/4: phpcs... 
Running task 2/4: phpunit... 
Running task 3/4: phpstan... 
Running task 4/4: eslint... ✘
eslint
======
/resources/js/app.js
23:1   error    Expected indentation of 4 spaces but found 8  indent
✖ 1 problem (1 error, 0 warnings)
1 error …
```

Add ESLint Task

---

.travis.yml

Make Travis green again on PHP 8!

---

resources/config/formatter.yml
resources/config/tasks.yml
src/Formatter/ComposerNormalizeFormatter.php
src/Task/ComposerNormalize.php
test/Unit/Task/ComposerNormalizeTest.php

This PR makes the `composer_normalize` task output a suggested command to fix errors, inspired by what the `phpcs` task does.

Suggest command to fix composer_normalize errors

---

src/IO/ConsoleIO.php

| Fixed tickets | #787, #770 
This PR reverts to an older version of the ConsoleIO in a safer way:
https://github.com/phpro/grumphp/commit/bad47d21ffd434667f550af6206834b1479fd467

Fix broken stdin

---

doc/tasks/phpmd.md
src/Task/PhpMd.php
test/Unit/Task/PhpMdTest.php

Since [2.8](https://phpmd.org/#phpmd-2-8-0-2019-12-18-) phpmd has a new, subjectively nicer, report format that is ansi
**ansi**
**text (current)**
I did not set the default to ansi for this PR, as the renderer is not available in older versions of phpmd

[phpmd] Allow setting output format to ansi

---

doc/tasks/composer_normalize.md
src/Task/ComposerNormalize.php
test/Unit/Task/ComposerNormalizeTest.php

composer-normalize is also available as a stand-alone PHAR (https://github.com/ergebnis/composer-normalize#phar).
This PR adds a new option to call this stand-alone command instead of `composer normalize`.

Add a way to call the standalone composer-normalize command

---

README.md
src/Console/Command/Git/InitCommand.php
src/Util/Filesystem.php
test/Unit/Util/FilesystemTest.php

| Fixed tickets | #416
This PR introduces a way of backup up existing git hooks.
It only backs them up if the old content does not match the new content.
This can be handy for testing a couple of different versions without atually removing them.
It also helps to recover a custom hook on first install as described in issue #416.

Create smart backups of existing git hooks

---

spec/Collection/FilesCollectionSpec.php
spec/Exception/ProcessExceptionSpec.php
src/Collection/FilesCollection.php
src/Exception/ProcessException.php
src/Process/InputWritingProcessRunner.php
src/Process/TmpFileUsingProcessRunner.php
src/Task/PhpLint.php
src/Task/Phpcs.php
src/Test/Task/AbstractExternalTaskTestCase.php
test/Unit/Task/PhpcsTest.php

| Fixed tickets | #523, #487, #275
New tools:
Makes it possible to run a process whilst streaming to stdin:
```php
// used in PhpLint task
$process = InputWritingProcessRunner::run(
function () use ($arguments): Process {
return $this->processBuilder->buildProcess($arguments);
},
static function () use ($files) {
yield $files->toFileList();
}
);
```
Makes it possible to run a process whilst adding a temporary file with dynamic content to the cli command:
```php
// used in PhpCs task
$process = TmpFileUsingProcessRunner::run(
function (string $tmpFile) use ($config): Process {
$arguments = …
```

Improved file passing tools

---

doc/commands.md
resources/config/console.yml
resources/config/locators.yml
resources/config/services.yml
spec/IO/ConsoleIOSpec.php
spec/Locator/ListedFilesSpec.php
spec/Locator/RegisteredFilesSpec.php
spec/Locator/StdInFilesSpec.php
src/Console/Command/Git/CommitMsgCommand.php
src/Console/Command/Git/PreCommitCommand.php
src/Console/Command/RunCommand.php
src/IO/ConsoleIO.php
src/Locator/ListedFiles.php
src/Locator/RegisteredFiles.php
src/Locator/StdInFiles.php

| Fixed tickets | #394
This PR allows adding files to GrumPHP through stdin.
Example:
```sh
git diff | php ./vendor/bin/grumphp run
git diff --staged | php ./vendor/bin/grumphp run
git ls-files src | php ./vendor/bin/grumphp run
cat some-file-with-one-path-per-line.txt | php ./vendor/bin/grumphp run
```
This works for the commands: `run`, `git:pre-commit`, `git:commit-msg`

Provide a stdin way of configuring files that need to be validated by GrumPHP

---

doc/tasks/git_blacklist.md
src/Task/Git/Blacklist.php
test/Unit/Task/Git/BlacklistTest.php

Added a match_word option to git blacklist.
Closes: #803
| Fixed tickets | #803
So I figured my issue #803 out by myself, as it turns out `git grep` command has an option called word `--word-regexp` or `-w` for sorthand.
This has been taken from the [Git scm documentation](https://git-scm.com/docs/git-grep)
```
Match the pattern only at word boundary 
(either begin at the beginning of a line, or preceded by a non-word character; end at the end of a line or followed by a non-word character).
```
I have added the possiblity to opt-in to this functionallity by using the new `match_word` …

Add `match_word` option to git blacklist task

---

doc/tasks/phpstan.md
src/Task/PhpStan.php
src/Test/Task/AbstractExternalTaskTestCase.php
test/Unit/Task/PhpStanTest.php

| Fixed tickets | #568, #512
This task adds a flag to the PhpStan task, so that you can choose whether you want GrumPHP to pass the list of changed files or not.
```yaml
grumphp:
tasks:
phpstan:
use_grumphp_paths: true
```

Phpstan: use_grumphp_paths option

---

resources/config/tasks.yml
src/Task/Git/CommitMessage.php
test/Unit/Task/Git/CommitMessageTest.php

| Branch        | #757, #729
| Fixed tickets | #757, #729
* Fixes #757 : a regex bug in the type conventions
* Fixes #729 : Respect core.commentChar config

minor git_commit_message improvements

---

doc/tasks/ecs.md
src/Task/Ecs.php
test/Unit/Task/EcsTest.php

| Branch        | #726
| Fixed tickets | #726, #652
This PR renames the `whitlist_patterns` option inside the ECS task to `paths`, making it less confusing.
It also updates the documentation to give you better information on how to configure the task.
Besides that, it also adds the `files_on_pre_commit` as suggested in PR #652

ecs: rename whitelist_patterns to paths and add files_on_pre_commit

---

composer.json
doc/tasks.md
doc/tasks/pest.md
resources/config/tasks.yml
src/Task/Pest.php
test/Unit/Task/PestTest.php

| Fixed tickets | #811 
Add PestPHP https://pestphp.com to GrumPHP :rocket: 
Task done with :heart: for Pest.
Execution with an output error (for show):

[Task] add Pest 

---

spec/Git/GitRepositorySpec.php
src/Git/GitRepository.php
src/Task/Git/CommitMessage.php
test/Unit/Task/Git/CommitMessageTest.php

| Fixed tickets | #813
Fixes #813
This PR contains  a safer way of fetching git configuration values.

Add a fail-safe fallback for fetching git config values

---

composer.json

Current package name is not up-to-date for symplify/easy-coding-standard within the suggest section of the composer.json. It is correct in the documentation though: https://github.com/phpro/grumphp/blob/master/doc/tasks/ecs.md#ecs---easycodingstandard

Change easycodingstandard package name in suggest

---

src/Locator/ExternalCommand.php

When Grumphp throws an ExecutableNotFoundException via the ExternalCommand class it executes sprintf twice because the Exception contains the sprintf as well.. This was probably introduced during refactoring of the Exception. This pull request just removes the obsolete sprintf.
https://github.com/phpro/grumphp/blob/0e6287a3ae70a8730d11a239449e991b3fc78f99/src/Exception/ExecutableNotFoundException.php#L12
**Example of output before:**
```
phpmd
=====
The executable for "The executable for "phpmd" could not be found." could not be found.
```
**Example of output after:**
```
phpmd
=====
The executable …
```

Remove obsolete sprintf from ExecutableNotFoundException callback

---

doc/installation/exotic.md
doc/runner.md
doc/tasks.md

Even though I can see that grumphp allows for both yml and yaml configuration files like it is supposed to:
https://github.com/phpro/grumphp/blob/0e6287a3ae70a8730d11a239449e991b3fc78f99/src/Locator/GuessedPathsLocator.php#L109-L112
I think semantically it's best to stay consistent through out the documentation to only reference one of the allowed extensions. A quick search showed that yml was the prefered extension:
- 11 results in 6 files for grumphp.yaml
- 148 results in 71 files for grumphp.yml
This pull request changes the extension in the documentation only. No code is touched. Maybe we could …

Consistently use yml instead of yaml extension in documentation

---

doc/tasks/phpcpd.md

When executing phpcpd through grumphp with the default settings copied from the documentation page to my grumphp.yml file it throws the following error:
```
In OptionsResolver.php line 871:
The options "names_exclude", "regexps_exclude" do not exist. Defined option  
s are: "directory", "exclude", "fuzzy", "min_lines", "min_tokens", "trigger  
ed_by".  
```
This pull requests removes the unknown options from the documentation page.

Remove unknown options from phpcpd task documentation

---

doc/tasks/twigcs.md

| Bug fix?      | yes/no
| BC breaks?    | yes/no
| Deprecations? | yes/no
| Documented?   | yes/no
With the default settings for the twigcs task in Grumphp we require the >=4.0 versions:
https://github.com/phpro/grumphp/blob/b8354000dc6e177ab1e77c06817876f11bb6c879/src/Task/TwigCs.php#L19-L25
Earlier version like ^3.0 have a different namespace:
https://github.com/friendsoftwig/twigcs/blob/7c4bc76dad8d851045b9eeab4979a240550f8300/src/Ruleset/Official.php#L3
For that I think it's best that we change the documentation line to require the >=4 version of this package.

Twig min version

---

src/Task/Ecs.php
test/Unit/Task/EcsTest.php

The Ecs task now returns a `FixableTaskResult` allowing it to work with the `fixer` parameter.

Made Ecs task fixable

---

src/Task/Git/CommitMessage.php
test/Unit/Task/Git/CommitMessageTest.php

GitFlow uses this syntax automatically when merging branches:
Merge release 'x.y.z'
Merge tag 'x.y.z' into develop
This PR fixes GrumPHP failing when merging a GitFlow branch with `git flow release finish`.

fix(CommitMessage): merge branch and tag syntax was failing with GitFlow

---

composer.json
resources/config/runner.yml
src/Runner/Ci/CiDetector.php
src/Runner/Reporting/TaskResultsReporter.php
test/Unit/Runner/Ci/CiDetectorTest.php

| Fixed tickets | #817
This PR creates a less verbose output on non-ansi systems like Github actions, Travis, ...
You can switch the behaviour by adding `--ansi` or `--no-ansi` flag.

Improve no-ansi reporting

---

src/Configuration/Configuration.php

We have two separate YAML files like this:
```yaml
---
grumphp:
tasks:
composer: ~
```
```yaml
---
imports:
- resource: grumphp2.yml
grumphp:
tasks:
composer_normalize: ~
```
This does not work because the import does not merge the task array correctly.
If I dump it, the merged array looks like this:
```yaml
tasks:
composer: ~
1: ~
```
And it will crash with this error:
```
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to GrumPHP\Exception\TaskConfigResolverException::unknownTask() must be of the type string, int given, called in /home/pierre/workspace/drupal_d9/vendor/phpro/grumphp/src/Conf …
```

Allow merging tasks

---

doc/tasks/git_blacklist.md

Fixed regex special characters not escaped in example code.

---

resources/hooks/local/commit-msg
resources/hooks/local/pre-commit

| Fixed tickets | #849
Fixes path whitespace issue in git hooks.

Fix git hooks error if the path contains whitespace

---

composer.json
src/Task/Paratest.php
test/Unit/Task/ParatestTest.php

| Bug fix?      | yes/no
| Fixed tickets | #853
This PR fixes the new paratest --verbose flag implementation (in 6.1.1).

Fix Paratest 6.1.1 syntax

---

doc/tasks/deptrac.md
src/Task/Deptrac.php
test/Unit/Task/DeptracTest.php

Deptrac has updated formatter options in `v0.9.0`. They enabled new formatters (e.g. baseline, table) and refactored existing formatters (e.g. Graphviz). This means that the previous options are not working anymore. New options are introduced for existing formatters.
This PR adds all new formatters with its new options to the `DeptracTask`.
_See commit descriptions for further information._
- https://github.com/sensiolabs-de/deptrac#formatters
- https://github.com/sensiolabs-de/deptrac/blob/master/CHANGELOG.md#090---2020-10-30

Implement refactored formatter options for Deptrac >= v0.9.0

---

src/Event/Subscriber/StashUnstagedChangesSubscriber.php

| Fixed tickets | #859
This fixes a [git bug](https://www.spinics.net/lists/git/msg369520.html) that deletes files during `git stash pop --quiet`.
The bug is located in the git version that comes with Xcode 12, which many folks will be using on macOS Catalina/Big Sur.

Fix --quiet bug during git stash pop

---

src/Runner/Middleware/HandleRunnerMiddleware.php
test/Unit/Runner/Middleware/HandleRunnerMiddlewareTest.php

| Fixed tickets | #860
Previous, task execution stopped when receiving non blocking failure results.
In this PR, `stop_on_failure` only stops if the failure result is actually blocking.

Only stop on failure for blocking failure results

---

doc/parameters.md
src/Runner/TaskHandler/Middleware/ParallelProcessingMiddleware.php

| Fixed tickets | #856
`amp/parallel-functions` is not copying the env variables from the parent into the child process automatically.
This fix enriches the `$_ENV` variables from the child process with the once set from the parent process.
The amp child process will pass the `$_ENV` during task execution to the task process in `symfony/process` (IF the value of the env variable is a string)

Pass $_ENV  variables to amp/parallel callback

---

src/Configuration/Compiler/TaskCompilerPass.php
src/Configuration/Compiler/TestSuiteCompilerPass.php

Fixes #869
Fix current psalm errors on master:
```
psalm
=====
ERROR: PossiblyInvalidIterator - src/Configuration/Compiler/TaskCompilerPass.php:37:18 - Cannot iterate over scalar (see https://psalm.dev/165)
foreach ($configuredTasks as $taskName => $config) {
ERROR: PossiblyInvalidArgument - src/Configuration/Compiler/TaskCompilerPass.php:79:73 - Argument 1 of array_keys expects array<array-key, mixed>, possibly different type array<array-key, mixed>|non-empty-scalar provided (see https://psalm.dev/092)
$container->setParameter('grumphp.tasks.configured', array_keys($configuredTasks));
ERROR: PossiblyNullIterator - src/Configuration/Compiler/TestSuiteCompilerPass.php:23:18 - Cannot iterate over nullable var array<array-key, mixed>|null|scalar (see https://psalm.dev/097)
foreach …
```

Fix psalm errors

---

src/Task/PhpStan.php
test/Unit/Task/PhpStanTest.php

This adds a check on the 'use_grumphp_paths' config before skipping so this task runs even though there are no changed files when `use_grumphp_paths` is set to false.

Check config before skipping

---

doc/tasks/git_branch_name.md
src/Task/Git/BranchName.php
test/Unit/Task/Git/BranchNameTest.php

| Fixed tickets | #866
`git_branch_name` fails if any of the items in the list fail.
PR changes so that any matching item in the whitelist will return a success unless already featured in the blacklist.

Test should not fail because it didn't match everything in the whitelist

---

doc/tasks/twigcs.md

Fixes #876
Add to the documentation that the path should exist or be accessible.
In FriendsOfTwig\Twigcs\Config\ConfigResolver:
```
if (!file_exists($absolutePath)) {
throw new InvalidConfigurationException(sprintf('The path "%s" is not readable.', $path));
}
```

#876 Update twigcs.md

---

doc/tasks/phpcsfixer.md

This is what is happening when looking for documentation and then you find something that can be fixed inline with Github in 10 seconds.

Fix extremelly minor typos.

---

doc/parameters.md

The "additional_info" parameter from "parameters.md" was misspelled.

Fix parameter typo in example

---

doc/tasks/twigcs.md
src/Task/TwigCs.php
test/Unit/Task/TwigCsTest.php

TwigCS supports a `display` option in order to [restrict output](https://github.com/friendsoftwig/twigcs#restricting-output) to only the ones that blocks the success of the command, this PR add the support for it.
An extra commit adds a test for the existing `severity` option that was missing.

Add support for display option to TwigCS task

---

src/Task/PhpCpd.php
test/Unit/Task/PhpCpdTest.php

In PhpCpd 6.0.0 there're few changes in CLI options: https://github.com/sebastianbergmann/phpcpd/blob/master/ChangeLog.md#600---2020-08-13 which make GrumPHP failing.
However, in current implementation, the suffix argument is passed in this way: `--suffix=*.php,*.myextension`
PhpCpd is expecting this argument in this format: `--suffix=.php --suffix=.myextension`
This PR Updates the way this argument is passed to the PhpCpd command.
Regards

Fix suffix property for PhpCpd v6

---

doc/tasks/phpunit.md
doc/tasks/phpunitbridge.md
src/Task/Phpunit.php
src/Task/PhpunitBridge.php
test/Unit/Task/PhpunitBridgeTest.php
test/Unit/Task/PhpunitTest.php

adds order-by argument to phpunit and phpunitBridge tasks

---

src/Task/Paratest.php
test/Unit/Task/ParatestTest.php

| Fixed tickets | #887
Solves incorrectly passed arguments to paratest.

Fix #887 - Paratest: parallel- and configuration-argument was passed incorrectly

---

doc/tasks/git_commit_message.md
src/Task/Git/CommitMessage.php
test/Unit/Task/Git/CommitMessageTest.php

I work in a Russian-speaking team and type/scope checks fails when the subject is written in only Russian.
it would be great if we can define type_scope_conventions.subject_pattern like:
```yaml
type_scope_conventions:
- types: []
- scopes: ~
- subject_pattern: >-
([a-zA-Zа-яА-Я0-9-_ #@'\/\"]+)
```

Add subject pattern configurable option

---

doc/tasks.md
doc/tasks/stylelint.md
resources/config/tasks.yml
src/Task/Stylelint.php
test/Unit/Task/ESLintTest.php
test/Unit/Task/StylelintTest.php

Add a task to support [Stylelint](https://stylelint.io/) tool.
Heavily inspired from the existing ESLint task.
Supports relevant CLI supported arguments, based on the `--help` output, the inspiration for the sorting.
Parameter description is comming from [the official documentation](https://stylelint.io/user-guide/usage/cli)
Extra commit for a small CS fix in ESLint test.

Add Stylelint task

---

doc/tasks.md
doc/tasks/securitychecker/roave.md
resources/config/tasks.yml
src/Task/SecurityCheckerRoave.php
test/Unit/Task/SecurityCheckerRoaveTest.php

| Fixed tickets | |
Contrary to what # #873 stated, I needed one more security checker!  
The new security-checker allows projects already using [roave/security-advisories](https://github.com/Roave/SecurityAdvisories) to do a security-check using grumphp.

Add security-checker using roave/security-advisories

---

composer.json

| Deprecations? |no
Allow upgrade of ondram/ci-detector dependency. After reading [the changelog](https://github.com/OndraM/ci-detector/blob/4.1.0/CHANGELOG.md) there is no BC break.

Allow ondram/ci-detector ^4.0 upgrade

---

doc/tasks/composer_normalize.md
src/Task/ComposerNormalize.php
test/Unit/Task/ComposerNormalizeTest.php

| Q               | A
| --------------- | ---
| Version         | `GrumPHP 1.5.0`
| Bug?            | no
| New feature?    | yes
| Question?       | no
| Documentation?  | no
| Related tickets | #595 , #596 , #645 , #944, #945
composer-normalize introduced `--no-check-lock ` option in [2.7.0](https://github.com/ergebnis/composer-normalize/releases/tag/2.7.0) release back in August  2020. 
This option is very useful when you work on a  library project and you only concerned about the `composer.json` file but not that much about the lock file that only exists in the development environment for the library itself.
It would be awesome to see it available via configuration for the `composer_normalize` task.

Add --no-check-lock option support

---

src/Task/Psalm.php

The list of output formats GrumPHP used was a bit outdated. This is now in sync with what's supported by latest and greatest Psalm.

Update Psalm output formats

---

README.md

Fixes a link in the README. Perhaps it would be better to just inline this as a snippet, or make a separate `composer.json.example` (or some such) file that won't get out of sync with the link here.

Fix link to composer.json suggest section

---

doc/tasks/eslint.md
src/Task/ESLint.php
test/Unit/Task/ESLintTest.php

| Fixed tickets | https://github.com/phpro/grumphp/discussions/961
Use native ignore-path option from [ESLint](https://eslint.org/docs/user-guide/configuring/ignoring-code#using-an-alternate-file).

Add ignore_path option for ESLint task

---

doc/tasks/deptrac.md
src/Task/Deptrac.php
test/Unit/Task/DeptracTest.php

| New feature?  | yes (improvement ?)
Deptrac `analyse` command syntax was changed since 0.19.

Change deptrac arguments according v0.19

---

doc/tasks/stylelint.md

I could not install stylelint without `install` in the command.
```
C:\Users\Johan>npm -g stylelint
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path C:\Users\Johan/package.json
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\Johan\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Johan\AppData\Local\npm-cache\_logs\2022-02-09T15_43_57_459Z-debug.log
C:\Users\Johan>npm install -g stylelint
added 179 packages, and audited 181 …
```

Incorrect global install for stylelint task

---

doc/tasks/securitychecker/local.md
src/Task/SecurityCheckerLocal.php
test/Unit/Task/SecurityCheckerLocalTest.php

Since v1.2 (https://github.com/fabpot/local-php-security-checker/blob/main/CHANGELOG.md#120-2021-09-21) in the **local-php-security-checker** is available a new `--no-dev` option for skipping `require-dev` packages.

New `no-dev` option for local-php-security-checker

---

doc/tasks/jsonlint.md

Fix incorrect syntax highlighting in [jsonlint.md](https://github.com/phpro/grumphp/blob/6315b5270977ea7171bca3c76745c2c4287d89f4/doc/tasks/jsonlint.md)
Regards.

Fix jsonlint.md syntax highlighting

---

doc/tasks.md
spec/Task/Config/MetadataSpec.php
src/Configuration/Compiler/TaskCompilerPass.php
src/Console/ApplicationConfigurator.php
src/Task/Config/Metadata.php

This PR allows for dynamically enable a task. Usefull for conventions so that you can configurably run a task or not through parameters.
Examples:
```yaml 
parameters:
run_security_advisories: true
grumphp:
tasks:
securitychecker_roave:
jsonfile: ./composer.json
lockfile: ./composer.lock
run_always: true
metadata:
enabled: "%run_security_advisories%"
```

Task enabled

---

doc/tasks/infection.md
src/Task/Infection.php
test/Unit/Task/InfectionTest.php

Infection does have cli options to directly show the escaped mutations on run (apart from the logfiles). 
However, by default, these are disabled, but can be enabled with the option `--show-mutations`. In verbose mode (`-v`), the non-covered escaped mutations will be shown as well.
@see https://infection.github.io/guide/command-line-options.html#show-mutations-or-s

Infection: Add missing `show_mutations` (incl. verbose mode)

---

.github/workflows/grumphp.yml

Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: naveen <172697+naveensrinivasan@users.noreply.github.com>

chore: Set permissions for GitHub actions

---

doc/tasks/deptrac.md
src/Task/Deptrac.php
test/Unit/Task/DeptracTest.php

Deptrac provides a `--cache-file` option to control where its cache file will be stored. This PR adds support for it with a new `grumphp.tasks.deptrac.cache_file` option in `grumphp.yml`, i.e.:
```
grumphp:
tasks:
deptrac:
cache_file: ~
```
I updated the corresponding unit test. I didn't see any functional tests, but I manually tested it and it worked great.

Add 'cache_file' parameter to 'deptrac' task.

---

src/Configuration/Configuration.php
test/Unit/Configuration/ConfigurationTest.php

| Fixed tickets | #1022
Fixes `ascii: null` config.

Make it possible to null out ascii config

---

doc/tasks/phparkitect.md

Follow-up of #1038
the default value of the stop_on_failure option is no longer null, but false.

Update phpArkitect default value for stop_on_failure to false

---

src/Task/ESLint.php
test/Unit/Task/ESLintTest.php

| Fixed tickets | #911
Adds deprecation flag to whitelist_patterns when providing a null value.
Also changed the default value to an empty array.

Added deprecation to whitelist_patterns with null value

---

composer.json
doc/tasks.md
doc/tasks/rector.md
resources/config/tasks.yml
src/Task/Rector.php
test/Unit/Task/RectorTest.php

| Branch        | rector
This PR adds a task to run Rector with grumphp

Add Rector Task

---

doc/tasks/phpcsfixer.md

PHP-CS-Fixer 3.0 where released in may 3, 2021. Latest 2.x where in nov 15, 2021.
Updated default configuration and cache filename. [Upgrade guide from 2.x to 3.0](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/UPGRADE-v3.md).

PHP-CS-Fixer 2.x to 3.0

---

README.md
src/Locator/GuessedPathsLocator.php

| Fixed tickets | #1069 
I didn't modify `GrumPHPTest\Unit\Locator` or `GrumPHPTest\Unit\Util\FilesystemTest` as all current naming options for `.yaml` weren't present.

Add support for grumphp.dist.{yml,yaml}

---

.github/workflows/grumphp.yml

Fixes the deprecations/warnings in the GitHub Actions workflow.
As per the warning, without this change the actions will error and fail starting from June.
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Fix workflow deprecations
