- README.md
> fix typo in additional requirements

- README.md
- composer.json
- resources/config/services.yml
- spec/GrumPHP/Locator/ChangedFilesSpec.php
- spec/GrumPHP/Locator/ExternalCommandSpec.php
- src/GrumPHP/Composer/GrumPHPPlugin.php
- src/GrumPHP/Console/Application.php
- src/GrumPHP/Console/Command/ConfigureCommand.php
- src/GrumPHP/Console/Command/Git/InitCommand.php
- src/GrumPHP/Console/Helper/PathsHelper.php
- src/GrumPHP/Locator/ChangedFiles.php
- src/GrumPHP/Locator/ExternalCommand.php
- src/GrumPHP/Task/Phpcs.php
- src/GrumPHP/Task/Phpspec.php
- src/GrumPHP/Task/Phpunit.php
> Windows compatibility + gitlib

- README.md
- resources/config/services.yml
- spec/GrumPHP/Task/BehatSpec.php
- src/GrumPHP/Task/Behat.php
Currently supported options:
--suite
--format
--config
--stop-on-failure
> Add a behat task

- README.md
This is a WIP...
So far took care of the YAML sections ...
> README.md prettification

- README.md
- src/GrumPHP/Configuration/GrumPHP.php
- src/GrumPHP/Console/Command/Git/InitCommand.php
- src/GrumPHP/Console/Command/Git/PreCommitCommand.php
- src/GrumPHP/Console/Helper/PathsHelper.php
Some people have bad sense of humor, so i added some configs for ascii images. Now you can change them or even disable.
> Configurable ascii images

- spec/GrumPHP/Locator/ChangedFilesSpec.php
- src/GrumPHP/Locator/ChangedFiles.php
A small tweak to check only the files staged for commit. Currently it's checking all the files and it's not very convenient if you have files that you are still working on.
> Check only the files that are staged for commit

- README.md
- resources/config/services.yml
- spec/GrumPHP/Task/BlacklistSpec.php
- src/GrumPHP/Task/Blacklist.php
Hi guys.
Here is new task. 
It cancel commit if blacklisted keywords will be found and prevent adding `var_dump(`, `die(` and whatever you want to your commits.
Hope this will be useful for other developers.
--
Thank you for really cool tool.
> Added: Blacklist task

- README.md
- src/GrumPHP/Composer/GrumPHPPlugin.php
Hi, guys. 
Can you please merge and tag release?
> Issue36 default config path

- src/GrumPHP/Composer/GrumPHPPlugin.php
- src/GrumPHP/Console/Application.php
- src/GrumPHP/Console/Command/ConfigureCommand.php
Hi again.
One more think I've missed first time...
(Tag it please :))
> Fixed: Use config path from composer's extra at config command

- resources/config/services.yml
- spec/GrumPHP/Collection/ProcessArgumentsCollectionSpec.php
- spec/GrumPHP/Task/Git/BlacklistSpec.php
- spec/GrumPHP/Task/PhpcsSpec.php
- spec/GrumPHP/Task/PhpcsfixerSpec.php
- src/GrumPHP/Collection/ProcessArgumentsCollection.php
- src/GrumPHP/Exception/ExceptionInterface.php
- src/GrumPHP/Exception/FailureException.php
- src/GrumPHP/Exception/FileNotFoundException.php
- src/GrumPHP/Exception/InvalidArgumentException.php
- src/GrumPHP/Exception/RuntimeException.php
- src/GrumPHP/Task/Behat.php
- src/GrumPHP/Task/Git/Blacklist.php
- src/GrumPHP/Task/Phpcs.php
- src/GrumPHP/Task/Phpcsfixer.php
- src/GrumPHP/Task/Phpspec.php
- src/GrumPHP/Task/Phpunit.php
This PR fixes issue #19.
A ProcessArgumentsCollection class is added which makes it much easier to configure the attributes of an external command in a task.
> Make it easier to apply arguments to an external task. 

- README.md
- doc/tasks/grunt.md
- resources/config/services.yml
- spec/GrumPHP/Task/GruntSpec.php
- src/GrumPHP/Task/Grunt.php
This PR contains a configurable grunt task which can be used for some frontend checks before running a commit.
> Introduce the Grunt task

- README.md
- doc/tasks.md
- doc/tasks/composer.md
- grumphp.yml
- resources/config/services.yml
- spec/GrumPHP/Task/ComposerSpec.php
- src/GrumPHP/Task/Composer.php
This task will run composer validation when the composer.json file has changed.
> Introduce Composer validation task

- README.md
- doc/tasks.md
- doc/tasks/xmllint.md
- doc/tasks/yamllint.md
- grumphp.yml
- resources/config/linters.yml
- resources/config/services.yml
- resources/config/tasks.yml
- spec/GrumPHP/Collection/FilesCollectionSpec.php
- spec/GrumPHP/Collection/LintErrorsCollectionSpec.php
- spec/GrumPHP/Linter/LintErrorSpec.php
- spec/GrumPHP/Linter/Xml/XmlLintErrorSpec.php
- spec/GrumPHP/Linter/Yaml/YamlLintErrorSpec.php
- spec/GrumPHP/Linter/Yaml/YamlLinterSpec.php
- spec/GrumPHP/Task/AbstractLinterTaskSpec.php
- spec/GrumPHP/Task/YamlLintSpec.php
- src/GrumPHP/Collection/FilesCollection.php
- src/GrumPHP/Configuration/ContainerFactory.php
- src/GrumPHP/Linter/LintError.php
- src/GrumPHP/Linter/Xml/XmlLintError.php
- src/GrumPHP/Linter/Yaml/YamlLintError.php
- src/GrumPHP/Linter/Yaml/YamlLinter.php
- src/GrumPHP/Task/AbstractLinterTask.php
- src/GrumPHP/Task/YamlLint.php
- test/fixtures/linters/yaml/invalid.yml
- test/fixtures/linters/yaml/object-support.yml
- test/fixtures/linters/yaml/valid.yml
- test/src/GrumPHPTest/Linter/Yaml/YamlLinterTest.php
This task improves the base linter classes + adds a YamlLint task.
> Introduce the YAML linter.

- README.md
- composer.json
- doc/tasks.md
- doc/tasks/security_checker.md
- grumphp.yml
- resources/config/tasks.yml
- spec/GrumPHP/Task/SecurityCheckerSpec.php
- src/GrumPHP/Task/SecurityChecker.php
I have create a task which will run the SensioLabs Security Checker. This is a command line tool that checks if your application uses dependencies with known security vulnerabilities. It uses the SensioLabs Security Check Web service and the Security Advisories Database.
More information here: [https://github.com/sensiolabs/security-checker](https://github.com/sensiolabs/security-checker)
Tests and documentation are included in this pull requests.
> Added security checker task

- README.md
- doc/parameters.md
- doc/tasks.md
- grumphp.yml
- resources/config/parameters.yml
- resources/config/services.yml
- spec/GrumPHP/Collection/TasksCollectionSpec.php
- spec/GrumPHP/Configuration/GrumPHPSpec.php
- spec/GrumPHP/Event/Subscriber/ProgressSubscriberSpec.php
- spec/GrumPHP/Runner/TaskRunnerSpec.php
- src/GrumPHP/Collection/TasksCollection.php
- src/GrumPHP/Configuration/GrumPHP.php
- src/GrumPHP/Event/Subscriber/ProgressSubscriber.php
- src/GrumPHP/Runner/TaskRunner.php
This commit implements the new features described in #84 and #16.
> Implement stop_on_failure and task priority

- README.md
- appveyor.yml
- spec/GrumPHP/Process/ProcessBuilderSpec.php
- src/GrumPHP/Locator/RegisteredFiles.php
> Add Windows CI

- composer.json
- resources/config/services.yml
- spec/GrumPHP/IO/ConsoleIOSpec.php
- spec/GrumPHP/IO/NullIOSpec.php
- src/GrumPHP/Console/Application.php
- src/GrumPHP/IO/ConsoleIO.php
- src/GrumPHP/IO/IOInterface.php
- src/GrumPHP/IO/NullIO.php
> Add logger + IO classes for easy logging

- doc/tasks/git_blacklist.md
- spec/GrumPHP/Collection/FilesCollectionSpec.php
- spec/GrumPHP/Task/Git/BlacklistSpec.php
- src/GrumPHP/Collection/FilesCollection.php
- src/GrumPHP/Task/Git/Blacklist.php
- src/GrumPHP/Task/Grunt.php
Fixes #101 and specifies an easy way to filter based on extensions.
> Make it possible to specify extensions for the git blacklist task.

- .github/issue_template.md
- .github/pull_request_template.md
This PR provides default templates for creating github issues / PRs.
The goal is to get better feedback from the reporter so that we can discover bugs easily.
In case of PR we will get better feedback on what the code changes in the library.
> Add default github templates for issues and templates.

- doc/tasks/phpcs.md
- spec/GrumPHP/Task/PhpcsSpec.php
- src/GrumPHP/Task/Phpcs.php
| Fixed tickets | 117
Added the ability to trigger Phpcs on files other than '.php' like '.module'
> Add file list to trigger Phpcs on

- README.md
- composer.json
- doc/tasks.md
- doc/tasks/ant.md
- doc/tasks/gulp.md
- doc/tasks/make.md
- doc/tasks/phing.md
- doc/tasks/robo.md
- doc/tasks/shell.md
- resources/config/tasks.yml
- spec/GrumPHP/Task/AntSpec.php
- spec/GrumPHP/Task/GulpSpec.php
- spec/GrumPHP/Task/MakeSpec.php
- spec/GrumPHP/Task/PhingSpec.php
- spec/GrumPHP/Task/RoboSpec.php
- spec/GrumPHP/Task/ShellSpec.php
- src/GrumPHP/Task/Ant.php
- src/GrumPHP/Task/Gulp.php
- src/GrumPHP/Task/Make.php
- src/GrumPHP/Task/Phing.php
- src/GrumPHP/Task/Robo.php
- src/GrumPHP/Task/Shell.php
This PR contains tasks for frequently used task runners: ant, phing, gulp, make, shell and robo.
Currently the implementations are pretty basic, but should do the job.
> Additional taskrunner tasks

- README.md
- composer.json
- doc/tasks.md
- doc/tasks/gherkin.md
- resources/config/tasks.yml
- spec/GrumPHP/Task/GherkinSpec.php
- src/GrumPHP/Task/Gherkin.php
| Fixed tickets | #128 
This PR contains a task for validating Gherkin feature files.
> Gherkin lint task

- composer.json
> fabpot-cs-fixer is abandoned, use the friendsofphp version instead

- doc/tasks/phpcs.md
- spec/GrumPHP/Task/PhpcsSpec.php
- src/GrumPHP/Task/Phpcs.php
There is encoding param support for phpcs task.
> PhpCs Specifying an Encoding

- resources/hooks/local/commit-msg
- resources/hooks/local/pre-commit
- resources/hooks/vagrant/commit-msg
- resources/hooks/vagrant/pre-commit
| Fixed tickets | #159 
This PR escapes special characters like the EOT (\c) character in a DIFF.
> Escape special characters in the git diff.

- resources/config/formatter.yml
- resources/config/tasks.yml
- spec/GrumPHP/Formatter/PhpcsFormatterSpec.php
- spec/GrumPHP/Task/PhpcsSpec.php
- src/GrumPHP/Formatter/PhpcsFormatter.php
- src/GrumPHP/Task/Phpcs.php
This adds phpcbf suggestions for the phpcs task.
it looks somthing like this:
````bash
FILE: /var/www/Classes/Command/CacheCommandController.php
----------------------------------------------------------------------
FOUND 4 ERRORS AFFECTING 3 LINES
----------------------------------------------------------------------
28 | ERROR | [x] Opening brace of a class must be on the line after
|       |     the definition
36 | ERROR | [x] Opening brace should be on a new line
49 | ERROR | [x] Expected 1 newline at end of file; 0 found
49 | ERROR | [x] The closing brace for the class …
```
> [FEATURE] add suggestions to phpcs Task (use phpcbf)

- resources/config/tasks.yml
- spec/GrumPHP/Task/PhpCsFixerV2Spec.php
- src/GrumPHP/Task/PhpCsFixerTrait.php
- src/GrumPHP/Task/PhpCsFixerV2.php
> Added php cs fixer v2

- doc/tasks/composer.md
- spec/GrumPHP/Task/ComposerSpec.php
- src/GrumPHP/Task/Composer.php
| Fixed tickets | #120, #116
This is a follow-up ticket for PR #120.
> Llaville feature/composer no local repository

- src/GrumPHP/Linter/Yaml/YamlLinter.php
- test/fixtures/linters/yaml/object-support-old.yml
- test/fixtures/linters/yaml/object-support.yml
- test/src/GrumPHPTest/Linter/Yaml/YamlLinterTest.php
| Tests pass?   | no
| Fixed tickets | #177
> Make it possible to lint with both Symfony <3.1 and >=3.1

- README.md
- composer.json
- doc/tasks.md
- doc/tasks/atoum.md
- resources/config/tasks.yml
- spec/GrumPHP/Collection/ProcessArgumentsCollectionSpec.php
- spec/GrumPHP/Task/AtoumSpec.php
- src/GrumPHP/Collection/ProcessArgumentsCollection.php
- src/GrumPHP/Task/Atoum.php
[Atoum](http://atoum.org/) is unit test framework that could totally be run in a grumphp task. This is an implementation of its usage containing specs and doc.
> Add atoum task

- README.md
- composer.json
- doc/tasks.md
- doc/tasks/phpcpd.md
- resources/config/tasks.yml
- spec/GrumPHP/Task/PhpCpdSpec.php
- src/GrumPHP/Task/PhpCpd.php
> Add PhpCpd task

- composer.json
- resources/config/formatter.yml
- resources/config/services.yml
- resources/config/tasks.yml
- spec/GrumPHP/Formatter/GitBlacklistFormatterSpec.php
- spec/GrumPHP/IO/ConsoleIOSpec.php
- spec/GrumPHP/Task/Git/BlacklistSpec.php
- src/GrumPHP/Configuration/ContainerFactory.php
- src/GrumPHP/Console/Application.php
- src/GrumPHP/Console/Command/Git/CommitMsgCommand.php
- src/GrumPHP/Console/Command/Git/PreCommitCommand.php
- src/GrumPHP/Formatter/GitBlacklistFormatter.php
- src/GrumPHP/IO/ConsoleIO.php
- src/GrumPHP/Task/Git/Blacklist.php
Nicer Git Blacklist Task message for very long lines.
Example:
> [FEATURE] Git blacklist formatter

- README.md
Changed the suggested fabpot/php-cs-fixer to friendsofphp in the README.md
Old package is abandoned.
> Changed the suggested fabpot/php-cs-fixer to friendsofphp

- resources/config/services.yml
- spec/GrumPHP/Process/ProcessBuilderSpec.php
- src/GrumPHP/Console/Application.php
- src/GrumPHP/Process/ProcessBuilder.php
Documented?   | no
| Fixed tickets | #179
Per a discussion on issue #179, this PR outputs a copy of each task's command when the -vvv flag is used. I didn't update any docs, since I couldn't see where the -vvv flag is mentioned anywhere.
> Write command to output stream when -vvv flag is set

- src/GrumPHP/Process/ProcessBuilder.php
Make sure sensiolabs is always platinum.
> Fix sensiolabs platinum badge

- README.md
- composer.json
- doc/tasks.md
- doc/tasks/php7cc.md
- resources/config/tasks.yml
- spec/GrumPHP/Task/Php7ccSpec.php
- src/GrumPHP/Task/Php7cc.php
| Fixed tickets | #134 
It's my first PR, please check it carefully (specially the unmarked boxes) :) I did my best !
> Add php7cc task

- README.md
- src/GrumPHP/Console/Application.php
> Roadmap update

- composer.json
> Auto sort composer packages

- doc/tasks.md
- doc/tasks/composer_script.md
- resources/config/tasks.yml
- spec/GrumPHP/Task/ComposerScriptSpec.php
- src/GrumPHP/Task/ComposerScript.php
> [FEATURE] add composer_script task

- .travis.yml
- spec/GrumPHP/Collection/FilesCollectionSpec.php
More information about the issue:
https://github.com/phpDocumentor/TypeResolver/commit/e224fb2ea2fba6d3ad6fdaef91cd09a172155ccb
https://github.com/phpDocumentor/TypeResolver/releases/tag/0.2.1
> Fix nighly build

- composer.json
- src/GrumPHP/Event/Subscriber/StashUnstagedChangesSubscriber.php
> Make sure not to pop the changes on deprecation warnings.

- spec/GrumPHP/Console/Helper/PathsHelperSpec.php
- src/GrumPHP/Console/Helper/PathsHelper.php
| Fixed tickets | #237
This PR fixes #237 and adds some tests to make sure that we can detect issues with this code in the future.
> Bugfix: Custom ASCII cannot be loaded.

- README.md
- composer.json
- doc/commands.md
- doc/testsuites.md
- resources/config/parameters.yml
- spec/GrumPHP/Collection/TasksCollectionSpec.php
- spec/GrumPHP/Collection/TestSuiteCollectionSpec.php
- spec/GrumPHP/Configuration/GrumPHPSpec.php
- spec/GrumPHP/Console/Helper/TaskRunnerHelperSpec.php
- spec/GrumPHP/Exception/InvalidArgumentExceptionSpec.php
- spec/GrumPHP/Runner/TaskRunnerContextSpec.php
- spec/GrumPHP/Runner/TaskRunnerSpec.php
- spec/GrumPHP/TestSuite/TestSuiteSpec.php
- src/GrumPHP/Collection/TasksCollection.php
- src/GrumPHP/Collection/TestSuiteCollection.php
- src/GrumPHP/Configuration/Compiler/TestSuiteCompilerPass.php
- src/GrumPHP/Configuration/ContainerFactory.php
- src/GrumPHP/Configuration/GrumPHP.php
- src/GrumPHP/Console/Command/Git/CommitMsgCommand.php
- src/GrumPHP/Console/Command/Git/PreCommitCommand.php
- src/GrumPHP/Console/Command/RunCommand.php
- src/GrumPHP/Console/Helper/TaskRunnerHelper.php
- src/GrumPHP/Exception/InvalidArgumentException.php
- src/GrumPHP/Formatter/PhpcsFormatter.php
- src/GrumPHP/Runner/TaskRunner.php
- src/GrumPHP/Runner/TaskRunnerContext.php
- src/GrumPHP/TestSuite/TestSuite.php
- src/GrumPHP/TestSuite/TestSuiteInterface.php
| Fixed tickets | #50 
Todo's:
> Make it possible to specify testsuites

- doc/tasks/phpspec.md
- grumphp.yml.dist
- phpspec.yml
- spec/GrumPHP/Task/PhpspecSpec.php
- src/GrumPHP/Task/Phpspec.php
> Add format and verbose option to the phpspec task

- src/GrumPHP/Event/Subscriber/StashUnstagedChangesSubscriber.php
> Fix failing phpspec due to php startup warnings

- resources/config/services.yml
- spec/GrumPHP/Locator/ChangedFilesSpec.php
- src/GrumPHP/Locator/ChangedFiles.php
> Test if a file exists when using the git diff as a source

- doc/tasks/npm_script.md
- spec/GrumPHP/Task/NpmScriptSpec.php
- src/GrumPHP/Task/NpmScript.php
| Fixed tickets | https://github.com/phpro/grumphp/issues/250
Added an extra parameter 'is_run_task' in the npm_script task to make it possible to run custom npm scripts. eg. npm run lint.
> npm run is implemented in the npm_script task

- spec/GrumPHP/IO/ConsoleIOSpec.php
- src/GrumPHP/IO/ConsoleIO.php
| Fixed tickets | #254
This PR fixes an issue with git files that are being added to the staged area during git commit.
> Fix No run task with commit with phpstorm

- .github/pull_request_template.md
| Tests pass?   | STOP
I don't like this template, but putting that aside, the test question is redundant&mdash;that's what CI is for.
> Removed test question from PR template.

- .travis.yml
| Tests pass?   | why are you asking me
* Removed some code duplication in Travis install section.
* Added `--no-interaction` flag for all composer invocations implicitly using alias.
* Minor tweaks.
> Removed code duplication and tuned Travis config.

- .travis.yml
* Removed PHP version duplication from Travis config.
> Impeccable finetuning of Travis config

- spec/GrumPHP/Console/Helper/PathsHelperSpec.php
- spec/GrumPHP/Event/TaskFailedEventSpec.php
- spec/GrumPHP/IO/ConsoleIOSpec.php
- spec/GrumPHP/IO/NullIOSpec.php
- spec/GrumPHP/Linter/Xml/XmlLintErrorSpec.php
- spec/GrumPHP/Linter/Yaml/YamlLintErrorSpec.php
- spec/GrumPHP/Parser/Php/Configurator/TraverserConfiguratorSpec.php
- spec/GrumPHP/Task/ComposerSpec.php
- spec/GrumPHP/Task/PhpcsSpec.php
- spec/GrumPHP/Task/XmlLintSpec.php
- spec/GrumPHP/Task/YamlLintSpec.php
- src/GrumPHP/Exception/PlatformException.php
- src/GrumPHP/IO/ConsoleIO.php
- src/GrumPHP/Parser/Php/Configurator/TraverserConfigurator.php
- src/GrumPHP/Runner/TaskRunner.php
- src/GrumPHP/Task/Git/Blacklist.php
- src/GrumPHP/Task/JsonLint.php
- src/GrumPHP/Task/Phpunit.php
- src/GrumPHP/Util/Platform.php
- test/src/GrumPHPTest/Linter/Xml/XmlLinterTest.php
> Removed double blank lines.

- src/Console/Application.php
- src/Parser/Php/Configurator/TraverserConfigurator.php
- src/Parser/Php/Visitor/ForbiddenClassMethodCallsVisitor.php
- src/Parser/Php/Visitor/ForbiddenStaticMethodCallsVisitor.php
- src/Task/AbstractPhpCsFixerTask.php
- src/Task/Git/CommitMessage.php
Just some minor issues detected by [PHPStan](https://github.com/phpstan/phpstan). PR for a PHPStan task coming soon™.
> Fix various issues detected by PHPStan

- README.md
- appveyor.yml
- src/Task/JsonLint.php
- src/Task/Phpcs.php
- src/Task/XmlLint.php
- src/Task/YamlLint.php
Some small build improvements.
> Fix AppVeyor build issues.

- src/Configuration/ContainerFactory.php
> Remove unused imports.

- .travis.yml
- appveyor.yml
Nobody wants to see package suggestions at build time; that's just spam in our build logs.
> Do not show suggestions at build time.

- README.md
> Fix little typo in README.md

- src/Console/Command/Git/PreCommitCommand.php
> Fix hidden success message

- composer.json
- src/Composer/DevelopmentIntegrator.php
| Fixed tickets | #295
This PR will ensure that developers of this package have a working GrumPHP git hook.
> Enable git hook during development

- README.md
- doc/faq.md
| Fixed tickets | #265 
I'm making the documentation great again! You will love it.
> Making the documentation great again: Feature/#265

- doc/tasks/behat.md
- doc/tasks/codeception.md
- doc/tasks/kahlan.md
- doc/tasks/phing.md
- doc/tasks/php7cc.md
- doc/tasks/php_cs_fixer.md
- doc/tasks/php_cs_fixer2.md
- doc/tasks/phpcpd.md
- doc/tasks/phpcs.md
- doc/tasks/phpmd.md
- doc/tasks/phpparser.md
- doc/tasks/phpspec.md
- doc/tasks/phpunit.md
- doc/tasks/robo.md
- doc/tasks/security_checker.md
| New feature?  |no
| Fixed tickets | #265
Documentation added to the tasks that need a composer package
> Add composer require command to the tasks documentation

- LICENSE
| Bug fix?      |no
Bump the copyright year
> Bump the copyright year

- doc/tasks/git_blacklist.md
- spec/Task/Git/BlacklistSpec.php
- src/Task/Git/Blacklist.php
This PR allows to choose the regexp type for patterns in the git blacklist_task
> Introduce a new regexp_type for git_blacklist task

- resources/config/tasks.yml
| Bug fix?      | yes/
| Fixed tickets | #340
> Add correct configuration for the git conflict task

- doc/tasks/git_branch_name.md
Updated the (wrong) title to GIT branch name.
> Updated title of GIT branch name tasks

- doc/tasks/git_branch_name.md
> Updated git_branch_name.md

- doc/tasks/git_conflict.md
Lowercased the word 'conflict'.
> Updated git_conflict.md

- doc/tasks/phplint.md
Added the composer dependency to the docs.
> Updated phplint.md

- doc/tasks/phpparser.md
Changed some old references to git(php) blacklist
> Updated phpparser.md

- README.md
- doc/conventions.md
| Fixed tickets | #330
In this ticket there is more documentation on how to write convention checkers.
> Add additional information about how to create conventions

- doc/tasks/phpstan.md
> add installation guide

- doc/tasks/phpmnd.md
| Bug fix?      | yes/no
Fix typo on code blocks of the phpmnd doc
> Fix typo on code blocks of phpmnd doc

- doc/extensions.md
We rebranded our grumphp Extensions.
> Update the extensions links

- doc/faq.md
> documentation

- README.md
- doc/tasks.md
- doc/tasks/file_size.md
- resources/config/tasks.yml
- spec/Task/FileSizeSpec.php
- src/Task/FileSize.php
> Add file size task

- doc/tasks/xmllint.md
Added quotes in the triggered_by example
Keeps the docs in line with each other
> Updated xmllint example

- doc/tasks/git_blacklist.md
Added quotes in the triggered_by example
Keeps the docs in line with each other
> Updated git_blacklist example

- doc/tasks/phpcsfixer2.md
- resources/config/tasks.yml
- spec/Task/PhpCsFixerV2Spec.php
- src/Task/PhpCsFixerV2.php
| New feature?  | yes/no
| Fixed tickets | #371, #327, #386
> Fix phpcsfixer2 issues

- spec/Task/Git/CommitMessageSpec.php
- src/Task/Git/CommitMessage.php
| Documented?   | /
| Fixed tickets | #406
> Ignore max body width for commented lines in the commit message

- src/Task/FileSize.php
> Fix undefined property

- README.md
- doc/tasks.md
> Fix task lists in README and task docs

- src/Collection/FilesCollection.php
> Remove outdated docblock

- spec/Console/Helper/TaskRunnerHelperSpec.php
- spec/Event/RunnerFailedEventSpec.php
- spec/Locator/ConfigurationFileSpec.php
- spec/Process/AsyncProcessRunnerSpec.php
- spec/Process/ProcessBuilderSpec.php
- spec/Task/ComposerSpec.php
- spec/Task/Git/BlacklistSpec.php
- spec/Task/Git/CommitMessageSpec.php
- spec/Task/PhpCsFixerSpec.php
- spec/Task/PhpCsFixerV2Spec.php
> Fix some PSR2 violations

- doc/tasks/phpstan.md
- spec/Collection/FilesCollectionSpec.php
- spec/Task/PhpStanSpec.php
- src/Collection/FilesCollection.php
- src/Task/PhpStan.php
> Improve phpstan configuration

- appveyor.yml
- composer.json
- test/Linter/Json/JsonLinterTest.php
- test/Linter/Xml/XmlLinterTest.php
- test/Linter/Yaml/YamlLinterTest.php
- test/Parser/Php/Visitor/AbstractVisitorTest.php
Brought to you by [PHP CS Fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer)
> Upgrade PHPUnit

- doc/tasks/infection.md
| Bug fix?      | yes (doc fix)
The configuration key was documented twice.
> [Infection Task] Configuration key was documented twice

- README.md
Remove the unmaintainable list of suggestions in the readme file by a reference link to composer.json
> Remove composer suggestions

- grumphp.yml.dist
> Increase process timeout to resolve CI issues

- src/Console/Application.php
| Documented?   |no
| Fixed tickets | #464
Make the -c param work as intended.
> Fixes #464

- composer.json
That hasn't been my email address for some time, and it anyway seems more right to acknowledge the entire community. :)
> Fix the authors section of composer.json

- doc/tasks/infection.md
- spec/Collection/FilesCollectionSpec.php
- spec/Task/InfectionSpec.php
- src/Task/Infection.php
> Add ignore patterns for Infection task

- spec/Task/ComposerSpec.php
- src/Task/Composer.php
notice: Undefined index: repositories in /var/www/grumphp/src/Task/Composer.php line 136
> Fixed notice if repositories is not defined

- src/Task/Infection.php
| Documented?   | /
| Fixed tickets | https://github.com/infection/infection/pull/198
> Add ignore-msi-with-no-mutations

- doc/tasks.md
| Fixed tickets | #309
Fixes #309
> Docs:  Run same task twice with different configuration

- spec/Collection/FilesCollectionSpec.php
- spec/Task/FileSizeSpec.php
- src/Collection/FilesCollection.php
- src/Task/FileSize.php
| Fixed tickets | https://github.com/phpro/grumphp/pull/450
> Ignore symlinks filesize task

- README.md
| Documented?   |no
| Fixed tickets | Fixes #416
> Updated README.md to reflect that existing git hooks will get destroyed

- doc/parameters.md
- spec/Configuration/GrumPHPSpec.php
- src/Configuration/GrumPHP.php
| Fixed tickets | #530 
This pull requests allows users to provide a list of ascii files in their grumphp.yml. GrumPHP will choose one at random for each run.
> Choose a random ascii if list is provided #530

- src/Composer/DevelopmentIntegrator.php
- src/Composer/GrumPHPPlugin.php
- src/Configuration/GrumPHP.php
- src/Console/Application.php
- src/Console/Helper/PathsHelper.php
- src/Console/Helper/TaskRunnerHelper.php
- src/Locator/ConfigurationFile.php
- src/Parser/Php/Configurator/TraverserConfigurator.php
- src/Process/ProcessFactory.php
- src/Util/Regex.php
| Branch        | grumpy-seventies
| Fixed tickets | #482 
Add missing typehints and return types to prepare PHP7.0 upgrade
> Add missing typehints and return types

- src/Collection/ProcessArgumentsCollection.php
- src/Composer/GrumPHPPlugin.php
- src/Configuration/Compiler/TaskCompilerPass.php
- src/Console/Command/Git/InitCommand.php
- src/Console/Helper/PathsHelper.php
| Branch        | grumpy-seventies
| Fixed tickets | #482 
Add some missing type hints
> Add missing type hints

- test/fixtures/linters/xml/xsd-url-invalid.xml
- test/fixtures/linters/xml/xsd-url-valid.xml
Reverts phpro/grumphp#559
Problem is fixed.
> Revert "Host our own version of the symfony XSDs"

- doc/tasks/psalm.md
- spec/Task/PsalmSpec.php
- src/Task/Psalm.php
> Added parameter to toggle show info

- README.md
- composer.json
- doc/tasks.md
- doc/tasks/phpunitbridge.md
- resources/config/tasks.yml
- spec/Task/PhpunitBridgeSpec.php
- src/Task/PhpunitBridge.php
> Add phpunit bridge

- doc/tasks/git_branch_name.md
- spec/Task/Git/BranchNameSpec.php
> Add missing property

- doc/tasks/phplint.md
- spec/Task/PhpLintSpec.php
- src/Task/PhpLint.php
Add ignore patterns for PHPLint task
> Add ignore patterns for PHPLint task

- doc/tasks/git_branch_name.md
- spec/Task/Git/BranchNameSpec.php
- src/Task/Git/BranchName.php
| Branch        | grumpy-seventies
> Add whitelist and blacklist to GitBranchName

- src/Locator/ConfigurationFile.php
Fixes #576
| Fixed tickets |  #576
> Fix deprecation warning

- composer.json
> Bump up security-checker version to ^5.0 #603

- spec/Collection/ProcessArgumentsCollectionSpec.php
- spec/Task/PhpCsFixerSpec.php
- src/Collection/ProcessArgumentsCollection.php
- src/Process/ProcessFactory.php
- src/Task/AbstractPhpCsFixerTask.php
> Bugfix: convert splFileInfo to string

- doc/parameters.md
Fix markup in the documentation of the ascii parameter.
No
> Fix the code example markup for this disable documentation

- doc/extensions.md
Added my extension for EasyCodingStandard to the docs.
> Add EasyCodingStandard extension

- README.md
- composer.json
- doc/tasks.md
- doc/tasks/paratest.md
- resources/config/tasks.yml
- spec/Task/ParatestSpec.php
- src/Task/Paratest.php
A PR with only paratest, not all tasks in parallel, so we can get this merged faster
- [ x ] Is the README.md file updated?
- [ x ] Are the dependencies added to the composer.json suggestions?
- [ x ] Is the doc/tasks.md file updated?
- [ x ] Are the task parameters documented?
- [ x ] Is the task registered in the tasks.yml file?
- [ x ] Does the task contains phpspec tests?
- [ x ] Is the configuration having logical allowed types?
- [ x ] Does the task run in the correct context?
- [ x ] Is the `run()` method readable?
- [ x ] Is the `run()` …
> Add Paratest task

- spec/Collection/ProcessArgumentsCollectionSpec.php
- src/Collection/ProcessArgumentsCollection.php
- src/Task/PhpStan.php
> Improve level parameter of PhpStan task

- README.md
- composer.json
- doc/tasks.md
- doc/tasks/twigcs.md
- resources/config/tasks.yml
- spec/Task/TwigCsSpec.php
- src/Task/TwigCs.php
Check [Twig](https://twig.symfony.com/) coding standard based on [Allocine/TwigCs](https://github.com/allocine/twigcs) .
At the moment the only available standard is the [official one from twig](http://twig.sensiolabs.org/doc/coding_standards.html).
> Task TwigCs

- README.md
- appveyor.yml
- composer.json
- doc/parameters.md
- resources/config/parameters.yml
- resources/hooks/local/commit-msg
- resources/hooks/local/pre-commit
- resources/hooks/vagrant/commit-msg
- resources/hooks/vagrant/pre-commit
- spec/Configuration/GrumPHPSpec.php
- spec/Process/ProcessUtilsSpec.php
- src/Console/Command/Git/InitCommand.php
- src/Process/ProcessUtils.php
- test/Bootstrap.php
- test/E2E/AbstractE2ETestCase.php
- test/E2E/GitHookParametersTest.php
| Fixed tickets | #615 
See #615 - support running grumphp on multiple locally installed PHP versions.
> #615, Support other PHP executable

- spec/Util/StrSpec.php
- src/Util/Str.php
> Fix issue when no --tasks are specified

- doc/tasks/phpmnd.md
- spec/Task/PhpMndSpec.php
- src/Task/PhpMnd.php
| Branch          features
Relate with #639
> Add ignore funcs

- appveyor.yml
> AppVeyor CI is broken

- doc/tasks/ecs.md
> Update composer require package

- resources/config/locators.yml
- spec/Locator/ExternalCommandSpec.php
- spec/Process/ProcessBuilderSpec.php
- src/Composer/GrumPHPPlugin.php
- src/Console/Command/Git/InitCommand.php
- src/Locator/ExternalCommand.php
- src/Process/ProcessBuilder.php
- src/Util/Filesystem.php
- src/Util/Paths.php
- test/Unit/Util/FilesystemTest.php
- test/Unit/Util/PathsTest.php
This PR provides an alternate solution for #678.
It is a bit more flexible and a bit less magical this way.
> Improved git init params

- README.md
- resources/hooks/local/commit-msg
- resources/hooks/vagrant/commit-msg
- spec/Task/PhpcsSpec.php
* Adds shim as the preferred way of installing Grumphp
* Fixes a bug in the commit-msg command (When e.g. git username contains a space)
> Improve shim package

- src/Composer/DevelopmentIntegrator.php
```
> GrumPHP\Composer\DevelopmentIntegrator::integrate
Script GrumPHP\Composer\DevelopmentIntegrator::integrate handling the post-update-cmd event terminated with an exception
[ErrorException]                                           
proc_open() expects parameter 1 to be string, array given  
```
> Fix composer process version in development integrator

- doc/tasks/psalm.md
- src/Task/Psalm.php
| Fixed tickets | #719 
Add `output-format` argument to Psalm Task.
> Psalm add output-format argument

- test/Unit/Task/AntTest.php
> Rewrite ant tests

- test/E2E/AbstractE2ETestCase.php
Tests in PR #745 fail. This PR is to fix the failing tests
> Fix for removed method in symfony/process:5.0

- .travis.yml
Just update Travis to use php 7.4 instead of php 7.4snapshot
> [DX] travis - php 7.4snapshot to 7.4

- doc/parameters.md
Adding support of docksal in documentation.
> Add support to Docksal

- src/Task/PhpCpd.php
- test/Unit/Task/PhpCpdTest.php
> Update PhpCpd names-exclude property

- doc/tasks/phpcpd.md
- src/Task/PhpCpd.php
- test/Unit/Task/PhpCpdTest.php
| Fixed tickets | --
In PhpCpd 6.0.0 there're few changes in CLI options: https://github.com/sebastianbergmann/phpcpd/blob/master/ChangeLog.md#600---2020-08-13 which make GrumPHP failing.
> Fix properties for PhpCpd v6

- composer.json
- doc/tasks.md
- doc/tasks/tester.md
- resources/config/tasks.yml
- src/Task/Tester.php
- test/Unit/Task/TesterTest.php
| Fixed tickets | #481, #649
This PR adds a new Task: Nette Tester
(Ported from @tombevers work - but wasnt able to push to his branch)
> Nette Tester task

- composer.json
Changing the suggestion for the robo package to reflect what is in the documentation (https://github.com/phpro/grumphp/blob/master/doc/tasks/robo.md#robo). The current package within the suggest section of the composer.json (https://packagist.org/packages/codegyre/robo) is abandoned. It needs to be changed to consolidation/robo.
> Update suggest package for robo.

- doc/tasks/phpstan.md
- src/Task/PhpStan.php
- test/Unit/Task/PhpStanTest.php
| Fixed tickets | #819
This PR improves the default phpstan level.
> Change phpstans default level

- resources/hooks/local/commit-msg
- resources/hooks/local/pre-commit
- resources/hooks/vagrant/commit-msg
- resources/hooks/vagrant/pre-commit
| Branch        | *
| Fixed tickets | #835
Make gumphp work with git config diff.noprefix=true
> Make "git diff" behave more predictably #835

- .travis.yml
- composer.json
- src/Composer/GrumPHPPlugin.php
| BC breaks?    | ?
| Deprecations? | ?
| Fixed tickets | #843 
This PR adds support of PHP8 which going to be released 26/11/2020
> Allow PHP8

- appveyor.yml
- test/Unit/Runner/Promise/MultiPromiseTest.php
> Fix phpunit concurrency issue

- composer.json
> Upgrade paratest

- doc/parameters.md
> Fix git init command in parameters.md

- composer.json
This upgrades to the latest version of amphp/parallel-functions (to benefit from any maintenance work happening there)
> Upgrade to amphp/parallel-functions 1.0

- doc/extensions.md
| Bug fix?      | yes/**no**
| New feature?  | yes/**no**
| BC breaks?    | yes/**no**
| Deprecations? | yes/**no**
| Documented?   | **yes**/no
Added jonmldr/grumphp-doctrine-task to extensions.md
> Added jonmldr/grumphp-doctrine-task to extensions.md

- doc/tasks.md
> Fixed a typo in tasks.md

- src/Task/Composer.php
- test/Unit/Task/ComposerTest.php
| Fixed tickets | #879
Fixes #879.
> Fix composer task when packagist.org is disabled

- composer.json
This upgrades composer dev dependencies to latest versions that don't include the CVE.
https://blog.packagist.com/composer-command-injection-vulnerability/
Since this is a dev dependency, GrumPHP is not impacted by this.
> Upgrade composer DEV dependencies

- composer.json
> Upgrade dev dependencies

- doc/tasks/git_commit_message.md
This is PR to fix documentation sample to git commit message hooks with type scope correct works.
In the actual yml sample, don't work rules, is need change specification as I do.
> fix(docs): commit message yml sample

- doc/tasks/phpunit.md
- doc/tasks/phpunitbridge.md
- src/Task/Phpunit.php
- src/Task/PhpunitBridge.php
- test/Unit/Task/PhpunitBridgeTest.php
- test/Unit/Task/PhpunitTest.php
> Add exclude group option to PHPUnit and PHPUnitBridge

- composer.json
Update psr/container to V2 because grumphp prevent update due to PSR/container
> psr/container V2 support

- doc/commands.md
- doc/faq.md
- doc/parameters.md
- doc/tasks/eslint.md
- doc/tasks/gherkin.md
- doc/tasks/kahlan.md
- doc/tasks/npm_script.md
- doc/tasks/phan.md
- doc/tasks/phpcs.md
- doc/tasks/phplint.md
- doc/tasks/phpmnd.md
- doc/tasks/phpparser.md
- doc/tasks/shell.md
- doc/tasks/tester.md
- doc/tasks/twigcs.md
> update doc typos

- composer.json
Locking parallel functions for now. See #957
> Lock parallel functions

- doc/tasks/twigcs.md
- src/Task/TwigCs.php
- test/Unit/Task/TwigCsTest.php
| BC breaks?    | maybe
To allow TwigCS run faster on precommit by checking only changed files instead of all ones even non changed ones.
> Lighter twigcs on precommit

- doc/tasks/eslint.md
Found another npm installation problem. :)
> Incorrect global install for eslint task

- .github/workflows/grumphp.yml
- appveyor.yml
> Dont ignore platform reqs

- doc/tasks/git_blacklist.md
- src/Task/Git/Blacklist.php
- test/Unit/Task/Git/BlacklistTest.php
| Fixed tickets | https://github.com/phpro/grumphp/issues/857
> Add ignore_patterns to git_blacklist.

- composer.json
> Support Monolog 3

- composer.json
- doc/tasks.md
- doc/tasks/phparkitect.md
- resources/config/tasks.yml
- src/Task/PhpArkitect.php
- test/Unit/Task/PhpArkitectTest.php
> Arkitect support

- doc/tasks/rector.md
Rector package name is `rector/rector`: https://packagist.org/packages/rector/rector
> [Docs] Fix invalid Rector install command

- composer.json
This makes it possible for projects using grumphp to update doctrine/collections
> Add support for doctrine/collections v2

- doc/faq.md
- spec/Event/Subscriber/StashUnstagedChangesSubscriberSpec.php
- src/Event/Subscriber/StashUnstagedChangesSubscriber.php
> Ignore untracked files with ignore_unstaged_changes parameter
